Repository ocaml/dune, pull requests merged in 2023-12, with the labels that each got.

#9339 pkg: prevent user from setting with-test variable
  src/dune_pkg/solver_env.ml
  src/dune_pkg/variable_name.ml
  src/dune_pkg/variable_name.mli
  test/blackbox-tests/test-cases/pkg/prevent-user-setting-with-test.t
Labels: package management

#9338 refactor(pkg): rename directory to dir for consistency
  bin/common.ml
  src/dune_rules/clflags.ml
  src/dune_rules/clflags.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#9342 test(pkg): fix typo in conflicts test
  test/blackbox-tests/test-cases/pkg/conflicts.t
Labels: package management

#9340 feature(pkg): conflicts support
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_rules/package.ml
  test/blackbox-tests/test-cases/pkg/conflicts.t
Labels: package management

#9331 fix(pkg): lock directories in lock dirs are specified relative to workspace
  src/dune_rules/workspace.ml
Labels: package management

#9347 [coq] Correctly handle composed stdlib after coq lang 0.8
  doc/changes/9347_fix_coq_boot_bug.md
  src/dune_rules/coq/coq_rules.ml
  test/blackbox-tests/test-cases/coq/coqdoc-with-boot.t/run.t
  test/blackbox-tests/test-cases/coq/failed-config.t/run.t
  test/blackbox-tests/test-cases/coq/no-stdlib.t/run.t
Labels: coq

#9253 fix(pkg): use the same expansion in substitute actions
  src/dune_pkg/substs.ml
  src/dune_pkg/substs.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/subst-installed-variable.t
  test/blackbox-tests/test-cases/pkg/substitute.t
Labels: package management

#9355 test(pkg): duplicate lock directory configuration
  test/blackbox-tests/test-cases/pkg/duplicate-lock-dirs.t
Labels: package management

#9364 test: add test making sure download location of fetch is correct
  test/expect-tests/dune_pkg/fetch_tests.ml
Labels: package management

#9378 feature(pkg): add our package overlay to default repos
  bin/pkg/pkg_common.ml
  src/dune_pkg/workspace.ml
  src/dune_pkg/workspace.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
Labels: package management

#9386 refactor(pkg): simplify formula checking
  src/dune_pkg/resolve_opam_formula.ml
Labels: package management

#9373 feat(pkg): Remove `opam-repository-url` option
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  test/blackbox-tests/test-cases/pkg/additional-constraints.t
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
  test/blackbox-tests/test-cases/pkg/invalid-version.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockdir-tampering.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/blackbox-tests/test-cases/pkg/partial-filter-evaluation.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#9372 test: reproduction case for #9328
  test/blackbox-tests/test-cases/pkg/git-repo.t
Labels: bug, package management

#9393 fix(pkg): more filter partial evaluation
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
Labels: package management

#9252 fix(pkg): fix downloads on windows
  src/dune_pkg/fetch.ml
Labels: package management

#9398 fix(pkg): simplify associative slang operations
  src/dune_lang/slang.ml
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
  test/blackbox-tests/test-cases/pkg/run-converted-opam-commands.t
Labels: package management

#9391 doc: use console lexer for shell sessions
  doc/concepts/package-spec.rst
  doc/concepts/promotion.rst
  doc/concepts/variables.rst
  doc/coq.rst
  doc/documentation.rst
  doc/dune-files.rst
  doc/dune-libs.rst
  doc/faq.rst
  doc/hacking.rst
  doc/howto/bundle.rst
  doc/howto/formatting.rst
  doc/instrumentation.rst
  doc/jsoo.rst
  doc/melange.rst
  doc/quick-start.rst
  doc/reference/actions.rst
  doc/sites.rst
  doc/stanzas/include.rst
  doc/stanzas/toplevel.rst
  doc/tests.rst
  doc/usage.rst
Labels: docs

#9352 fix(pkg): Only parse `blob` objects into files
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/git-repo.t
Labels: package management

#9431 test: make sure depopts are optional
  test/blackbox-tests/test-cases/pkg/depopts-optional.t
Labels: package management

#9433 test: move depopts tests to own directory
  test/blackbox-tests/test-cases/pkg/depopts/depopts-optional.t
  test/blackbox-tests/test-cases/pkg/depopts/depopts.t
Labels: package management

#9441 test(pkg): conflict classes
  test/blackbox-tests/test-cases/pkg/conflict-class.t
Labels: package management

#9442 refactor(pkg): add conflict classes
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_rules/package.ml
Labels: package management

#9443 refactor(pkg): pass depopts along to solver
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_rules/package.ml
Labels: package management

#9440 test: conflicting depopts
  test/blackbox-tests/test-cases/pkg/depopts/depopts-with-conflicting-constraints.t
Labels: package management

#9432 test: translation of depopts field
  test/blackbox-tests/test-cases/pkg/depopts/opam-package-with-depopts.t
Labels: package management

#9444 test(pkg): fix repo creation
  test/blackbox-tests/test-cases/pkg/helpers.sh
Labels: package management

#9434 test: depopts with constraints
  test/blackbox-tests/test-cases/pkg/depopts/depopts-with-constraints.t
Labels: package management

#9418 pkg: read local package metadata from opam files
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_dependency.mli
  src/dune_rules/opam_create.ml
  src/dune_rules/package.ml
  src/dune_rules/package.mli
  test/blackbox-tests/test-cases/pkg/conflict-class.t
  test/blackbox-tests/test-cases/pkg/duplicate-packages.t
  test/blackbox-tests/test-cases/pkg/opam-file-errors.t
  test/blackbox-tests/test-cases/pkg/opam-only-metadata.t
Labels: package management

#9424 feature(pkg): add sys-ocaml-version variable
  src/dune_lang/pform.ml
  src/dune_lang/pform.mli
  src/dune_pkg/sys_poll.ml
  src/dune_pkg/sys_poll.mli
  src/dune_pkg/variable_name.ml
  src/dune_pkg/variable_name.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-os.t
Labels: package management

#9448 refactor(pkg): simplify formula evaluation
  src/dune_pkg/resolve_opam_formula.ml
Labels: package management

#9452 fix(pkg): unbreak ocaml-system
  src/dune_rules/ocaml_toolchain.ml
  src/dune_rules/ocaml_toolchain.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#9450 fix(pkg): use [Global.env ()] over [Env.initial]
  src/dune_rules/pkg_rules.ml
Labels: package management

#9420 doc: add cram lexer
  doc/conf.py
  doc/exts/cram_lexer.py
  doc/hacking.rst
  doc/tests.rst
Labels: docs

#9421 doc: move reference info about cram test stanza
  doc/dune-files.rst
  doc/stanzas/cram.rst
  doc/tests.rst
Labels: docs

#9384 pkg: compute checksums for packages without checksums
  bin/pkg/lock.ml
  src/dune_pkg/checksum.ml
  src/dune_pkg/checksum.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
Labels: package management

#9455 fix(pkg): remove the [DUNE_PKG_OVERRIDE_OCAML] hack
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/ocaml-compiler.t
Labels: package management

#9457 test: demonstrate solver bug with version self referencing
  test/blackbox-tests/test-cases/pkg/self-version-constraint.t
Labels: package management

#9453 pkg: unset variables in workspace file
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/print_solver_env.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
Labels: package management

#9462 fix(pkg): expand self reference variables
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_universe.ml
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/resolve_opam_formula.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_pkg/variable_name.ml
  src/dune_pkg/variable_name.mli
  test/blackbox-tests/test-cases/pkg/self-version-constraint.t
Labels: package management

#9343 pkg: remove context arguments
  bin/common.ml
  bin/common.mli
  bin/describe/describe_pkg.ml
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/print_solver_env.ml
  bin/pkg/validate_lock_dir.ml
  test/blackbox-tests/test-cases/pkg/conflict-class.t
  test/blackbox-tests/test-cases/pkg/conflicts.t
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/bar/bar.0.0.1/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/bar/bar.0.4.0/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/bar/bar.0.5.0/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/baz/baz.0.0.1/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/baz/baz.0.1.0/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/packages/foo/foo.0.0.1/opam
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/mock-opam-repository/repo
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/blackbox-tests/test-cases/pkg/prevent-user-setting-with-test.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#8921 fix(pkg): delay expansion of paths
  otherlibs/stdune/src/array.ml
  otherlibs/stdune/src/array.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/slang_expand.ml
  src/dune_rules/slang_expand.mli
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-switch.t
Labels: package management

#9241 feature(pkg): Support for specifying particular branches/commits for repos
  bin/pkg/pkg_common.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: package management

#9460 Update opam-file-generation.rst - Added line about generating only the opam file
  doc/howto/opam-file-generation.rst
Labels: docs

#9465 fix(pkg): remove --dont-poll-system-solver-variables
  bin/pkg/lock.ml
  bin/pkg/print_solver_env.ml
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/lockdir-tampering.t
  test/blackbox-tests/test-cases/pkg/prevent-user-setting-with-test.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#9468 chore(pkg): Add a test to make sure that picking a branch works
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: package management

#9469 chore(pkg): Set the XDG cache dir in the env, use just one in the test
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: package management

#9471 feature(pkg): Enable checking out tags
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: package management

#9512 Add (explain) field to (menhir) stanza
  bin/printenv.ml
  doc/changes/9512.md
  doc/stanzas/env.rst
  doc/stanzas/menhir.rst
  src/dune_lang/blang.ml
  src/dune_lang/blang.mli
  src/dune_rules/dune_env.ml
  src/dune_rules/dune_env.mli
  src/dune_rules/dune_rules.ml
  src/dune_rules/env_node.ml
  src/dune_rules/env_node.mli
  src/dune_rules/menhir/menhir_env.ml
  src/dune_rules/menhir/menhir_env.mli
  src/dune_rules/menhir/menhir_rules.ml
  src/dune_rules/menhir/menhir_stanza.ml
  src/dune_rules/menhir/menhir_stanza.mli
  test/blackbox-tests/test-cases/menhir/explain.t/parser.mly
  test/blackbox-tests/test-cases/menhir/explain.t/run.t
  test/blackbox-tests/test-cases/workspaces/workspace-env.t/run.t
Labels: menhir

#9509 pkg: version field in lockfile is mandatory
  src/dune_pkg/lock_dir.ml
  test/blackbox-tests/test-cases/pkg/command-from-user-path.t
  test/blackbox-tests/test-cases/pkg/default-exported-env.t
  test/blackbox-tests/test-cases/pkg/exported-env.t
  test/blackbox-tests/test-cases/pkg/external-source.t
  test/blackbox-tests/test-cases/pkg/extra-sources.t
  test/blackbox-tests/test-cases/pkg/file-depends.t
  test/blackbox-tests/test-cases/pkg/gh8325.t
  test/blackbox-tests/test-cases/pkg/git-source.t
  test/blackbox-tests/test-cases/pkg/install-action-dirs.t
  test/blackbox-tests/test-cases/pkg/install-action.t
  test/blackbox-tests/test-cases/pkg/install-entry-build-dir.t
  test/blackbox-tests/test-cases/pkg/install-missing-entry.t
  test/blackbox-tests/test-cases/pkg/installed-binary.t
  test/blackbox-tests/test-cases/pkg/libraries.t
  test/blackbox-tests/test-cases/pkg/lockdir-validation.t
  test/blackbox-tests/test-cases/pkg/make.t
  test/blackbox-tests/test-cases/pkg/ocaml-compiler.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-files-install.t
  test/blackbox-tests/test-cases/pkg/package-cycle.t
  test/blackbox-tests/test-cases/pkg/package-files.t
  test/blackbox-tests/test-cases/pkg/patch.t
  test/blackbox-tests/test-cases/pkg/per-context.t
  test/blackbox-tests/test-cases/pkg/pkg-action-when.t
  test/blackbox-tests/test-cases/pkg/pkg-deps.t
  test/blackbox-tests/test-cases/pkg/simple-lock.t
  test/blackbox-tests/test-cases/pkg/slang.t
  test/blackbox-tests/test-cases/pkg/subst-installed-variable.t
  test/blackbox-tests/test-cases/pkg/substitute.t
  test/blackbox-tests/test-cases/pkg/variables.t
  test/blackbox-tests/test-cases/pkg/withenv.t
Labels: package management

#9388 refactor: allow config values to be defined anywhere
  src/dune_config/config.ml
  src/dune_config/config.mli
  src/dune_rules/async.ml
  src/dune_rules/import.ml
Labels: upstream-sync

#9461 Fix for #9456
  doc/changes/9461.md
  src/dune_rules/odoc_new.ml
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/b.ml
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/b.mli
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/dune
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/dune-project
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/odoctest2.opam
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/run.t
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/sublib/a.ml
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/sublib/a.mli
  test/blackbox-tests/test-cases/odoc/new/multi-lib.t/sublib/dune
Labels: odoc

#9532 fix: concatenate strings before comparing
  src/dune_rules/slang_expand.ml
  test/blackbox-tests/test-cases/pkg/slang.t
Labels: package management

#9536 repro(pkg): Test the behavior with submodules
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: bug, package management

#9534 doc(pkg): Add documentation on how the revision store works
  doc/dev/rev-store.md
Labels: docs, package management

#9531 fix(pkg): prevent blang/slang infinite recursion
  src/dune_lang/blang.ml
  src/dune_lang/blang.mli
  src/dune_lang/slang.ml
  src/dune_rules/enabled_if.ml
  test/blackbox-tests/test-cases/pkg/slang.t
Labels: package management

#9557 pkg: include lockdirs with no context
  bin/pkg/pkg_common.ml
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/blackbox-tests/test-cases/pkg/solve-lockdir-without-context.t
Labels: package management

#9546 pkg: validate vars in lockdir against workspace
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/pkg-validate-on-build.t
Labels: package management

#9549 fix(pkg): Read the main branch correctly even if tags exist
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: bug, package management

#9506 feat(pkg): Implement downloading sources via git
  src/dune_pkg/fetch.ml
  src/dune_pkg/fetch.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/expect-tests/dune_pkg/fetch_tests.ml
Labels: package management

#9435 fix: add [O_CLOEXEC] to sendfile calls
  otherlibs/stdune/src/io.ml
Labels: upstream-sync

#9582 test(pkg): pin-depends support
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#9583 test(pkg): local sources in opam repo
  test/blackbox-tests/test-cases/pkg/opam-source-conversion.t
Labels: package management
