Repository ocaml/dune, pull requests merged in 2023-07, with the labels that each got.

#8106 refactor: use Path in odoc command
  src/dune_rules/odoc.ml
Labels: refactoring

#8108 refactor: String.quote_list_for_shell
  otherlibs/stdune/src/string.ml
  otherlibs/stdune/src/string.mli
  src/dune_engine/action_to_sh.ml
  src/dune_engine/process.ml
  src/dune_rules/context.ml
  src/dune_util/log.ml
  test/expect-tests/vcs_tests.ml
Labels: refactoring

#8109 refactor: use Command.Args.t for Modules.pp
  src/dune_rules/module_compilation.ml
  src/dune_rules/preprocessing.ml
Labels: refactoring

#8182 refactor(odoc): remove dummy file
  src/dune_rules/odoc.ml
  test/blackbox-tests/test-cases/odoc/github1645.t
  test/blackbox-tests/test-cases/odoc/multiple-private-libs.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/diff-scope.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/same-scope.t/run.t
Labels: odoc

#8211 Unify lockdir loading with functor
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/pkg_rules.ml
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#8091 Don't solve for multiple contexts if lockdirs collide
  bin/pkg.ml
  otherlibs/stdune/src/loc.ml
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/solver-flags-per-context.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#8105 feature(pkg): Automatic fetching of opam-repository
  bin/dune
  bin/pkg.ml
  src/dune_pkg/fetch.ml
  src/dune_pkg/fetch.mli
  src/dune_pkg/opam.ml
  src/dune_pkg/opam.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/solver-flags-per-context.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#8188 Solver can solve for multiple environments in single lockdir
  bin/pkg.ml
  otherlibs/ordering/ordering.ml
  otherlibs/ordering/ordering.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/opam.ml
  src/dune_pkg/opam.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/sys_poll.ml
  src/dune_pkg/sys_poll.mli
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/solver-flags-per-context.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#8237 Expose user environment when running pkg actions
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/command-from-user-path.t
Labels: package management

#8275 Don't warn on undefined opam variables when solving
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#8267 Set the opam-version variable during solving
  bin/pkg.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
Labels: package management
