Repository ocaml/dune, pull requests merged in 2023-11, with the labels that each got.

#9051 fix(pkg): add a candidates cache
  src/dune_pkg/opam_solver.ml
Labels: package management

#9052 fix: remove [loc] from rule digest
  doc/changes/9052.md
  src/dune_engine/build_system.ml
  test/blackbox-tests/test-cases/dune-cache/mode-copy.t
  test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
  test/blackbox-tests/test-cases/dune-cache/repro-check.t
  test/blackbox-tests/test-cases/dune-cache/trim.t
  test/blackbox-tests/test-cases/patch-back-source-tree.t
  test/blackbox-tests/test-cases/rule/digest.t/run.t
  test/blackbox-tests/test-cases/rule/dune
Labels: upstream-sync

#9065 refactor(pkg): use a single git call to load opam files
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
Labels: package management

#9068 pkg: check version constraints for lockfile deps
  src/dune_lang/package_constraint.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/resolve_opam_formula.mli
  test/blackbox-tests/test-cases/pkg/lockfile-deps-respect-constraints.t
Labels: package management

#9102 refactor: move some opam logic into dune_pkg
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/import.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_dependency.mli
  src/dune_pkg/package_name.ml
  src/dune_pkg/package_name.mli
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/substs.ml
  src/dune_rules/package.ml
  src/dune_rules/package.mli
Labels: package management

#9103 pkg: add Dune_pkg.Local_package module
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/package_version.ml
  src/dune_pkg/package_version.mli
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg_outdated/dune_pkg_outdated.ml
  src/dune_pkg_outdated/dune_pkg_outdated.mli
  src/dune_rules/package.ml
  src/dune_rules/package.mli
Labels: package management

#9110 fix description of `dune pkg print-solver-env`
  bin/pkg/print_solver_env.ml
Labels: package management

#9096 refactor(pkg): fetch all package extra files in a single call
  otherlibs/stdune/src/map.ml
  otherlibs/stdune/src/map_intf.ml
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/opam_solver.ml
Labels: package management

#9156 pkg: validate dependencies of packages in lockdir
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  test/blackbox-tests/test-cases/pkg/lockdir-validation.t
Labels: package management

#9150 refactor(pkg): remove copying hacks
  src/dune_rules/dir_contents.ml
  src/dune_rules/dir_status.ml
  src/dune_rules/dir_status.mli
  src/dune_rules/gen_rules.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_rules.mli
  test/blackbox-tests/test-cases/pkg/opam-package-with-files-install.t
Labels: package management

#8035 refactor(engine): optimize sandbox config storage
  src/dune_engine/build_system.ml
  src/dune_engine/sandbox_config.ml
  src/dune_engine/sandbox_mode.ml
  src/dune_engine/sandbox_mode.mli
  test/blackbox-tests/test-cases/dune-cache/mode-copy.t
  test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
  test/blackbox-tests/test-cases/dune-cache/repro-check.t
  test/blackbox-tests/test-cases/dune-cache/trim.t
  test/blackbox-tests/test-cases/patch-back-source-tree.t
Labels: upstream-sync

#9140 fix(pkg): Add a lock around the revision store
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/rev-store-lock.t
  test/expect-tests/dune_pkg/dune
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: package management

#9174 fix(pkg): proper error messages for bad config files
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/variables.t
Labels: package management

#9184 refactor: improve substitution in files
  src/dune_pkg/substs.ml
  src/dune_pkg/substs.mli
  src/dune_rules/pkg_rules.ml
  vendor/opam/src/format/opamFilter.mli
Labels: package management

#9172 Validate lockdir against local packages
  bin/pkg/pkg.ml
  bin/pkg/validate_lock_dir.ml
  bin/pkg/validate_lock_dir.mli
  src/dune_lang/package_constraint.ml
  src/dune_lang/package_constraint.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/package_universe.ml
  src/dune_pkg/package_universe.mli
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/resolve_opam_formula.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_rules/package.ml
  test/blackbox-tests/test-cases/pkg/lock-dir-local-package-sync.t
Labels: package management

#9221 chore: update vendored opam
  vendor/update-opam.sh
Labels: chore

#9114 pkg: add local packages hash to lockdir
  bin/describe/describe_pkg.ml
  bin/pkg/lock.ml
  src/dune_lang/package_constraint.ml
  src/dune_lang/package_constraint.mli
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/package_universe.ml
  src/dune_pkg_outdated/dune_pkg_outdated.ml
  test/blackbox-tests/test-cases/pkg/check-dependency-hash.t
  test/blackbox-tests/test-cases/pkg/dependency-hash.t
  test/blackbox-tests/test-cases/pkg/lockdir-tampering.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#9048 pkg: fix architecture detection on windows
  vendor/opam/src/core/custom_opamStubs.c
  vendor/opam/src/core/dune
  vendor/opam/src/core/opamStubs.ml
  vendor/update-opam.sh
Labels: windows, package management

#9236 refactor(pkg): inline some small function
  src/dune_rules/pkg_rules.ml
Labels: package management

#9249 test(pkg): remove invalid variables from substitute
  test/blackbox-tests/test-cases/pkg/substitute.t
Labels: package management

#9248 refactor(pkg): improve local package lookup
  src/dune_rules/package_db.ml
Labels: package management

#9095 pkg: detect test-only dependencies in lockdir
  bin/describe/describe_pkg.ml
  src/dune_pkg/package_universe.ml
  src/dune_pkg/package_universe.mli
  test/blackbox-tests/test-cases/pkg/test-only-deps.t
Labels: package management

#9254 fix(pkg): simplify attempt_to_lock
  src/dune_pkg/rev_store.ml
Labels: package management

#9245 fix(pkg): do not expose hashing scheme of dependency_hash in lock dir
  src/dune_pkg/local_package.ml
  test/blackbox-tests/test-cases/pkg/check-dependency-hash.t
  test/blackbox-tests/test-cases/pkg/dependency-hash.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
Labels: package management

#9262 refactor(pkg): rename tries to retries
  src/dune_pkg/rev_store.ml
Labels: package management

#9250 chore: add dune lang 3.13
  doc/coq.rst
  doc/dune-files.rst
  doc/foreign-code.rst
  doc/hacking.rst
  doc/instrumentation.rst
  doc/melange.rst
  doc/sites.rst
  otherlibs/dune-rpc/private/types.ml
  test/blackbox-tests/test-cases/directory-targets/installed-dependency.t
  test/blackbox-tests/test-cases/dune-init.t/run.t
  test/blackbox-tests/test-cases/install/install-stublibs.t/run.t
  test/blackbox-tests/test-cases/melange/basic-install.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: chore

#9255 fix(pkg): open rev lock with same settings as dune lock
  src/dune_pkg/rev_store.ml
Labels: package management

#9202 feature(pkg): Implement offline mode for Rev Store
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: enhancement, package management

#9269 test(pkg): invalid package dependency bug
  test/blackbox-tests/test-cases/pkg/invalid-version.t
Labels: package management

#9279 fix(pkg): never build dune
  src/dune_rules/pkg_rules.ml
Labels: package management

#9280 feature(coq): coqdoc_flags in env stanza
  bin/printenv.ml
  doc/changes/9280_coq_env.md
  doc/coq.rst
  doc/stanzas/env.rst
  src/dune_rules/coq/coq_env.ml
  src/dune_rules/coq/coq_env.mli
  src/dune_rules/coq/coq_flags.ml
  src/dune_rules/coq/coq_flags.mli
  src/dune_rules/coq/coq_rules.ml
  src/dune_rules/dune_env.ml
  src/dune_rules/dune_env.mli
  src/dune_rules/dune_rules.ml
  src/dune_rules/env_node.ml
  src/dune_rules/env_node.mli
  test/blackbox-tests/test-cases/coq/coqdoc-flags.t
  test/blackbox-tests/test-cases/workspaces/workspace-env.t/run.t
Labels: coq

#9259 fix(pkg): improve error checking of lock dir
  src/dune_pkg/lock_dir.ml
Labels: package management

#9263 refactor(pkg): use our own digest api rather than the stdlib's
  src/dune_pkg/local_package.ml
Labels: package management

#9257 Add `test_` prefix to default test name in `dune init project`
  bin/dune_init.ml
  doc/changes/9257.md
  doc/quick-start.rst
  test/blackbox-tests/test-cases/dune-init.t/run.t
Labels: dune init

#9009 fix: allow reuse of dispatch queues between fsevents in macOS
  src/fsevents/fsevents_stubs.c
Labels: macos

#9267 fix: use [O_CLOEXEC] when creating temp files
  otherlibs/stdune/src/temp.ml
Labels: upstream-sync

#9036 refactor: use [Unix.rename] over [Sys.rename]
  otherlibs/stdune/src/path.ml
  src/dune_cache_storage/util.ml
  test/blackbox-tests/test-cases/sandbox-remove-write-permissions.t
Labels: upstream-sync

#9301 test(ctypes): add repro for #9300
  test/blackbox-tests/test-cases/ctypes/types-only.t
Labels: ctypes

#9322 test(pkg): solver ignores conflicts
  test/blackbox-tests/test-cases/pkg/conflicts.t
Labels: package management

#9310 Add delay to address flaky fsevent test
  test/expect-tests/fsevents/fsevents_tests.ml
Labels: macos

#9319 feature(pkg): introduce lock_directory stanza in workspace
  bin/pkg/pkg_common.ml
  src/dune_rules/context.ml
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/git-repo.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/multiple-opam-repos.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock-linux.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#9325 pkg: simplify representation of solver variables
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/print_solver_env.ml
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_variable.ml
  src/dune_pkg/package_variable.mli
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_pkg/substs.ml
  src/dune_pkg/sys_poll.ml
  src/dune_pkg/sys_poll.mli
  src/dune_pkg/variable_name.ml
  src/dune_pkg/variable_name.mli
  src/dune_pkg/variable_value.ml
  src/dune_pkg/variable_value.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/slang_expand.ml
  src/dune_rules/slang_expand.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management
