Repository ocaml/dune, pull requests merged in 2023-05, with the labels that each got.

#7384 doc(coq): Add documentation for composition with installed theories
  doc/coq.rst
Labels: docs, coq

#7666 dune-rpc: use loopback address on Windows
  CHANGES.md
  otherlibs/dune-rpc/private/where.ml
Labels: windows

#7588 odoc: put odoc support files in odoc.support
  CHANGES.md
  src/dune_rules/odoc.ml
  test/blackbox-tests/test-cases/odoc/multiple-private-libs.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-simple.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/diff-scope.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/same-scope.t/run.t
Labels: odoc

#7669 melange: improve extension name
  src/dune_rules/melange/melange_stanzas.ml
Labels: melange

#7599 [coq] Deprecate Coq Lang < 0.8
  CHANGES.md
  doc/coq.rst
  doc/hacking.rst
  src/dune_rules/coq/coq_stanza.ml
  test/blackbox-tests/test-cases/coq/base-unsound.t/run.t
  test/blackbox-tests/test-cases/coq/base.t/run.t
  test/blackbox-tests/test-cases/coq/compose-boot-nodeps.t/run.t
  test/blackbox-tests/test-cases/coq/compose-boot-nodups.t/run.t
  test/blackbox-tests/test-cases/coq/compose-boot-nostdlib.t/run.t
  test/blackbox-tests/test-cases/coq/compose-boot-plugins.t/run.t
  test/blackbox-tests/test-cases/coq/compose-cycle.t/run.t
  test/blackbox-tests/test-cases/coq/compose-installed-compat.t/run.t
  test/blackbox-tests/test-cases/coq/compose-plugin.t/run.t
  test/blackbox-tests/test-cases/coq/compose-private-ambiguous.t/run.t
  test/blackbox-tests/test-cases/coq/compose-private.t/run.t
  test/blackbox-tests/test-cases/coq/compose-projects-boot.t/run.t
  test/blackbox-tests/test-cases/coq/compose-projects-cycle.t/run.t
  test/blackbox-tests/test-cases/coq/compose-projects-missing.t/run.t
  test/blackbox-tests/test-cases/coq/compose-projects-private-ambiguous.t/run.t
  test/blackbox-tests/test-cases/coq/compose-projects.t/run.t
  test/blackbox-tests/test-cases/coq/compose-self.t/run.t
  test/blackbox-tests/test-cases/coq/compose-simple.t/run.t
  test/blackbox-tests/test-cases/coq/compose-sub-theory.t/run.t
  test/blackbox-tests/test-cases/coq/compose-two-scopes.t/run.t
  test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/run.t
  test/blackbox-tests/test-cases/coq/coqdoc-dir-target-clash.t/run.t
  test/blackbox-tests/test-cases/coq/coqdoc-multi-theory.t/run.t
  test/blackbox-tests/test-cases/coq/coqdoc-with-boot.t/run.t
  test/blackbox-tests/test-cases/coq/coqdoc.t/run.t
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-nested.t/run.t
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-recomp.t
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-root.t/run.t
  test/blackbox-tests/test-cases/coq/deprecate-libraries.t/run.t
  test/blackbox-tests/test-cases/coq/deprecate-public_name.t/run.t
  test/blackbox-tests/test-cases/coq/empty-modules.t/run.t
  test/blackbox-tests/test-cases/coq/env.t
  test/blackbox-tests/test-cases/coq/extract.t
  test/blackbox-tests/test-cases/coq/extraction-patch.t/run.t
  test/blackbox-tests/test-cases/coq/flags.t
  test/blackbox-tests/test-cases/coq/github5532.t
  test/blackbox-tests/test-cases/coq/ml-lib.t/run.t
  test/blackbox-tests/test-cases/coq/native-compose.t/run.t
  test/blackbox-tests/test-cases/coq/native-single.t/run.t
  test/blackbox-tests/test-cases/coq/no-stdlib.t/run.t
  test/blackbox-tests/test-cases/coq/plugin-meta.t/run.t
  test/blackbox-tests/test-cases/coq/plugin-private.t/run.t
  test/blackbox-tests/test-cases/coq/public-dep-on-private.t/run.t
  test/blackbox-tests/test-cases/coq/rec-module.t/run.t
  test/blackbox-tests/test-cases/coq/theory-stanza-duplicate-module.t/run.t
Labels: coq

#7665 melange: set min version to 3.8
  CHANGES.md
  src/dune_rules/melange/melange_stanzas.ml
  test/blackbox-tests/test-cases/lib-modes.t
  test/blackbox-tests/test-cases/melange/add-rules-under-melange-emit-target.t
  test/blackbox-tests/test-cases/melange/aliases.t
  test/blackbox-tests/test-cases/melange/basic-install.t
  test/blackbox-tests/test-cases/melange/copy-files-include-subdirs.t
  test/blackbox-tests/test-cases/melange/copy-files-into-emit-target-folder.t
  test/blackbox-tests/test-cases/melange/copy-files-simple.t
  test/blackbox-tests/test-cases/melange/depend-on-installed.t
  test/blackbox-tests/test-cases/melange/dune-js-file-unmangling.t/dune-project
  test/blackbox-tests/test-cases/melange/dune-package-source-path.t
  test/blackbox-tests/test-cases/melange/emit-installed-complex.t/dune-project
  test/blackbox-tests/test-cases/melange/emit-installed-complex.t/inner/dune-project
  test/blackbox-tests/test-cases/melange/emit-installed-two-modes.t
  test/blackbox-tests/test-cases/melange/emit-installed.t
  test/blackbox-tests/test-cases/melange/emit-private.t
  test/blackbox-tests/test-cases/melange/emit-select.t
  test/blackbox-tests/test-cases/melange/emit-two-dune-projects.t
  test/blackbox-tests/test-cases/melange/empty-entries-target-dir-exists.t
  test/blackbox-tests/test-cases/melange/empty-entries.t
  test/blackbox-tests/test-cases/melange/flags.t
  test/blackbox-tests/test-cases/melange/gh7020.t
  test/blackbox-tests/test-cases/melange/include_subdirs.t/dune-project
  test/blackbox-tests/test-cases/melange/intfonly-entries.t
  test/blackbox-tests/test-cases/melange/intfonly.t/dune-project
  test/blackbox-tests/test-cases/melange/merlin-compile-flags.t
  test/blackbox-tests/test-cases/melange/merlin.t
  test/blackbox-tests/test-cases/melange/missing-melc.t
  test/blackbox-tests/test-cases/melange/mli.t/dune-project
  test/blackbox-tests/test-cases/melange/module-systems.t
  test/blackbox-tests/test-cases/melange/multilib.t/dune-project
  test/blackbox-tests/test-cases/melange/nested-melange-emit-stanzas.t
  test/blackbox-tests/test-cases/melange/ocaml-flags.t
  test/blackbox-tests/test-cases/melange/preprocess.t
  test/blackbox-tests/test-cases/melange/private-module.t/dune-project
  test/blackbox-tests/test-cases/melange/private.t/dune-project
  test/blackbox-tests/test-cases/melange/promote-with-lib.t
  test/blackbox-tests/test-cases/melange/promote.t
  test/blackbox-tests/test-cases/melange/public.t/dune-project
  test/blackbox-tests/test-cases/melange/rescript-syntax.t
  test/blackbox-tests/test-cases/melange/reused-module.t
  test/blackbox-tests/test-cases/melange/root-module.t
  test/blackbox-tests/test-cases/melange/runtime-deps-in-target-dir.t
  test/blackbox-tests/test-cases/melange/simple.t/dune-project
  test/blackbox-tests/test-cases/melange/target-validation.t
  test/blackbox-tests/test-cases/melange/two-emit-stanzas.t
  test/blackbox-tests/test-cases/melange/unmangling.t
  test/blackbox-tests/test-cases/melange/virtual_lib.t/dune-project
Labels: melange

#7652 test(melange): incorrect path when public lib depends on private lib
  test/blackbox-tests/test-cases/melange/private-lib-dep.t
Labels: melange

#7626 feature: build opam packages
  boot/libs.ml
  otherlibs/stdune/src/bin.ml
  otherlibs/stdune/src/bin.mli
  otherlibs/stdune/src/env.ml
  otherlibs/stdune/src/env.mli
  src/dune_lang/dune
  src/dune_lang/pform.ml
  src/dune_lang/pform.mli
  src/dune_rules/dune
  src/dune_rules/expander.ml
  src/dune_rules/expander.mli
  src/dune_rules/gen_rules.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_rules.mli
  test/blackbox-tests/test-cases/pkg/exported-env.t
  test/blackbox-tests/test-cases/pkg/external-source.t
  test/blackbox-tests/test-cases/pkg/install-action.t
  test/blackbox-tests/test-cases/pkg/installed-binary.t
  test/blackbox-tests/test-cases/pkg/simple-lock.t
  test/blackbox-tests/test-cases/pkg/variables.t
Labels: package management

#7695 test(pkg): install action
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/install-action-dirs.t
  test/blackbox-tests/test-cases/pkg/install-action.t
Labels: package management

#7685 test(melange): merlin generation
  test/blackbox-tests/test-cases/melange/merlin.t
Labels: merlin, melange

#7693 feature(pkg): version lock directory format
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/exported-env.t
  test/blackbox-tests/test-cases/pkg/external-source.t
  test/blackbox-tests/test-cases/pkg/install-action.t
  test/blackbox-tests/test-cases/pkg/installed-binary.t
  test/blackbox-tests/test-cases/pkg/simple-lock.t
  test/blackbox-tests/test-cases/pkg/variables.t
Labels: package management

#7696 feature(pkg): improve checksum handling
  src/dune_rules/pkg_rules.ml
Labels: package management

#7701 refactor(pkg): simplify entries in cookie
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/install-action.t
  test/blackbox-tests/test-cases/pkg/installed-binary.t
Labels: package management

#7697 fix(pkg): location handling for source copies
  src/dune_rules/pkg_rules.ml
Labels: package management

#7692 nix: remove unused rec and bump ocaml-base-compiler to 4.14.1
  flake.nix
Labels: nix

#7719 test(melange): interaction between melange_runtime_deps and include_subdirs
  test/blackbox-tests/test-cases/melange/installed-library-with-runtime-deps-include-qualified.t
Labels: melange

#7709 Bump ctypes stanza version to 0.3 in documentation
  doc/foreign-code.rst
Labels: docs, ctypes

#7683 doc: put uncategorized pages under the best header
  doc/index.rst
Labels: docs

#7738 doc: convert README.org in example to markdown
  example/hello_world.t/README.md
  example/hello_world.t/README.org
  example/with-configure-step.t/README.md
  example/with-configure-step.t/README.org
Labels: docs

#7718 fix(runtime_deps): check paths are descendant of the library root
  src/dune_rules/install_rules.ml
  test/blackbox-tests/test-cases/melange/installed-library-with-runtime-deps-nested-errors.t
Labels: melange

#7739 doc: add API docs for dune-build-info
  otherlibs/build-info/src/build_info.mli
  otherlibs/build-info/src/dune
  otherlibs/build-info/src/index.mld
Labels: docs

#7746 doc: point at the official docs in odoc
  doc/dune
  doc/index.mld
Labels: docs

#7734 feat(pkg-config): allow reading PKG_CONFIG_ARGN
  CHANGES.md
  otherlibs/configurator/src/v1.ml
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/config_test.ml
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/dune
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/dune-project
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/pkg-config.opam
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/run.t
  src/dune_rules/pkg_config.ml
Labels: configurator

#7756 configurator: document `PKG_CONFIG_PATH` and `PKG_CONFIG_ARGN`
  otherlibs/configurator/src/v1.mli
Labels: docs, configurator

#7749 doc: add odoc index for configurator
  otherlibs/configurator/src/dune
  otherlibs/configurator/src/index.mld
Labels: docs

#7775 doc: correct doc for (map_workspace_root)
  doc/dune-files.rst
Labels: docs

#7780 refactor(coq): remove indentation in coqtop
  bin/coq/coqtop.ml
Labels: coq

#7804 doc: expand actions documentation with a special directive
  doc/exts/sphinx_dunedomain.py
  doc/reference/actions.rst
Labels: docs

#7742 feature(pkg): set environment in build rules
  src/dune_lang/action.ml
  src/dune_lang/action.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/action_unexpanded.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/withenv.t
Labels: package management

#7842 doc: add xrefs to actions
  doc/dune-libs.rst
  doc/exts/sphinx_dunedomain.py
  doc/foreign-code.rst
  doc/reference/actions.rst
  doc/reference/predicate-language.rst
Labels: docs
