Repository ocaml/dune, pull requests merged in 2023-04, with the labels that each got.

#7380 dune coq top: add --no-build option to avoid building dependencies
  CHANGES.md
  bin/coq/coqtop.ml
  doc/coq.rst
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-no-build.t
Labels: coq

#7466 doc: split preprocessing into ref and explanation
  doc/concepts/preprocessing-spec.rst
  doc/explanation/preprocessing.rst
  doc/index.rst
  doc/reference/preprocessing-spec.rst
  doc/stanzas/library.rst
Labels: docs

#7469 dune-configurator: respect $PKG_CONFIG
  CHANGES.md
  otherlibs/configurator/src/v1.ml
  src/dune_rules/pkg_config.ml
Labels: configurator, cross-compilation

#7404 doc: improve synopsis for all commands
  bin/build_cmd.ml
  bin/cache.ml
  bin/coq/coqtop.ml
  bin/diagnostics.ml
  bin/format_dune_file.ml
  bin/help.ml
  bin/init.ml
  bin/install_uninstall.ml
  bin/ocaml/ocaml_cmd.ml
  bin/ocaml/ocaml_merlin.ml
  bin/ocaml/utop.ml
  bin/print_rules.ml
  bin/shutdown.ml
  bin/upgrade.ml
  test/blackbox-tests/test-cases/dune-cache/cache-man.t
Labels: docs

#7408 doc: allow for downloads of pdf and epub of documentation
  .readthedocs.yaml
Labels: docs

#7499 doc: move lexical conventions to reference
  doc/dune-files.rst
  doc/index.rst
  doc/reference/lexical-conventions.rst
Labels: docs

#7500 Add documentation on how to vendor code
  doc/hacking.rst
Labels: docs

#7450 test(x-compilation): demonstrate overlap check failure with ppx_runtime_libraries
  CHANGES.md
  src/dune_rules/lib.ml
  test/blackbox-tests/test-cases/custom-cross-compilation/ppx-runtime-libraries.t
  test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t
Labels: cross-compilation

#7479 doc: turn "Automatic Formatting" into a how-to
  doc/dune-files.rst
  doc/formatting.rst
  doc/howto/formatting.rst
  doc/index.rst
  doc/test/run.t
Labels: docs

#7428 x-compilation: take host findlib.conf into account when cross-compiling
  CHANGES.md
  src/dune_rules/context.ml
  src/dune_rules/findlib/findlib.ml
  src/dune_rules/findlib/findlib.mli
  test/blackbox-tests/test-cases/custom-cross-compilation/cross-compilation-ocamlfind.t
  test/blackbox-tests/test-cases/custom-cross-compilation/no-ocamlfind-in-path.t
  test/expect-tests/findlib_tests.ml
Labels: cross-compilation

#7505 Document advantage of `executables` over `executable`
  doc/stanzas/executable.rst
Labels: docs

#7551 refactor(melange): use `Dep_conf_eval.decode_no_files` in `runtime_deps`
  src/dune_rules/melange/melange_stanzas.ml
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps-edge-cases.t
Labels: melange

#7538 doc: merge classical-ppx into preprocessing-spec
  doc/advanced/classical-ppx.rst
  doc/index.rst
  doc/reference/preprocessing-spec.rst
Labels: docs

#7537 doc: add some info about writing docs
  doc/hacking.rst
Labels: docs

#7515 doc: turn opam.rst into 3 guides
  doc/concepts/package-spec.rst
  doc/dune-files.rst
  doc/explanation/opam-integration.rst
  doc/howto/opam-file-generation.rst
  doc/index.rst
  doc/opam.rst
  doc/overview.rst
  doc/quick-start.rst
  doc/reference/packages.rst
  doc/stanzas/library.rst
Labels: docs

#7574 doc: add a lexer for opam files
  doc/conf.py
  doc/explanation/opam-integration.rst
  doc/exts/opam_lexer.py
  doc/howto/opam-file-generation.rst
Labels: docs

#7567 doc: merge reference info about findlib
  doc/advanced/findlib-integration.rst
  doc/advanced/meta-file-generation.rst
  doc/index.rst
  doc/reference/findlib.rst
Labels: docs

#7477 doc(melange): write manual
  doc/melange.rst
Labels: docs, melange

#7609 doc: fix changelog
  CHANGES.md
Labels: docs

#7617 chore: update melange
  Makefile
  flake.lock
  flake.nix
  src/dune_engine/action.ml
  test/blackbox-tests/test-cases/melange/copy-files-include-subdirs.t
  test/blackbox-tests/test-cases/melange/copy-files-simple.t
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps-dir-target.t
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps-edge-cases.t
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps.t
  test/blackbox-tests/test-cases/melange/installed-library-with-runtime-deps.t
  test/blackbox-tests/test-cases/melange/library-with-runtime-deps.t
  test/blackbox-tests/test-cases/melange/merlin.t
  test/blackbox-tests/test-cases/melange/public-library-with-runtime-deps.t
Labels: melange

#7612 doc(melange): Move the example project to the top
  doc/melange.rst
Labels: docs, melange

#7623 fix: melange bench
  .github/workflows/bench.yml
Labels: melange

#7621 melange: test dune rules subcommand
  test/blackbox-tests/test-cases/melange/dune-rules.t
Labels: melange

#7582 feature: mdx 0.4 stanza with support for `mld` files out of the box
  CHANGES.md
  doc/stanzas/mdx.rst
  src/dune_rules/mdx.ml
  test/blackbox-tests/test-cases/mdx-stanza/mld-files.t
Labels: mdx
