Repository ocaml/dune, pull requests merged in 2023-10, with the labels that each got.

#8805 refactor: centralize workaround for OCaml bug
  otherlibs/stdune/src/io.ml
  otherlibs/stdune/src/path.ml
  src/dune_cache/local.ml
Labels: upstream-sync

#8807 refactor: remove pointless exception catch-all
  otherlibs/stdune/src/path.ml
Labels: upstream-sync

#8766 fix(pkg): remove wildcard behaviour for sys vars
  bin/pkg.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#8857 fix(pkg): correctly filter "|" dependencies
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
Labels: package management

#8596 Experimental string list language
  bin/pkg.ml
  src/dune_lang/action.ml
  src/dune_lang/action.mli
  src/dune_lang/blang.ml
  src/dune_lang/blang.mli
  src/dune_lang/dune_lang.ml
  src/dune_lang/slang.ml
  src/dune_lang/slang.mli
  src/dune_lang/string_with_vars.ml
  src/dune_lang/string_with_vars.mli
  src/dune_pkg/import.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/package_variable.ml
  src/dune_pkg/package_variable.mli
  src/dune_rules/action_unexpanded.ml
  src/dune_rules/dune_file.ml
  src/dune_rules/enabled_if.ml
  src/dune_rules/import.ml
  src/dune_rules/merlin/merlin.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/preprocess.ml
  src/dune_rules/slang_expand.ml
  src/dune_rules/slang_expand.mli
  src/dune_rules/test_rules.ml
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-pkg.t
  test/blackbox-tests/test-cases/pkg/run-converted-opam-commands.t
  test/blackbox-tests/test-cases/pkg/slang.t
  vendor/opam/src/format/opamFilter.mli
  vendor/update-opam.sh
Labels: package management, notify-benchmark-results

#8894 doc: fix missing parenthesis
  doc/stanzas/executable.rst
Labels: docs

#8852 feature(pkg): include local test deps
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
Labels: package management

#8899 feature(pkg): add implicit constraint on dune
  src/dune_pkg/opam_solver.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: package management

#8906 refactor: s/hard_link/hardlink/
  src/dune_cache/local.ml
Labels: upstream-sync

#8876 fix(pkg): correctly verify tarball checksums
  src/dune_pkg/fetch.ml
  test/expect-tests/dune_pkg/fetch_tests.ml
  vendor/opam/src/format/opamTypes.mli
  vendor/opam/src/repository/opamDownload.ml
  vendor/opam/src/repository/opamDownload.mli
  vendor/opam/src/repository/opamHTTP.ml
  vendor/opam/src/repository/opamRepository.ml
Labels: package management

#8904 fix: add fake opam switch to opam-var tests
  test/blackbox-tests/test-cases/pkg/opam-var/dune
  test/blackbox-tests/test-cases/pkg/opam-var/fake_opam_root/config
  test/blackbox-tests/test-cases/pkg/opam-var/fake_opam_root/default/.opam-switch/switch-config
Labels: package management

#8773 feature(pkg): dune pkg outdated
  bin/dune
  bin/import.ml
  bin/pkg.ml
  boot/libs.ml
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg_outdated/dune
  src/dune_pkg_outdated/dune_pkg_outdated.ml
  src/dune_pkg_outdated/dune_pkg_outdated.mli
  src/dune_pkg_outdated/import.ml
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/expect-tests/dune_pkg_outdated/dune
  test/expect-tests/dune_pkg_outdated/dune_pkg_outdated_test.ml
  test/expect-tests/dune_pkg_outdated/dune_pkg_outdated_test.mli
Labels: package management

#8925 Use precise ranges in patches in pkg tests
  test/blackbox-tests/test-cases/pkg/opam-package-subst-patch.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-patch-multiple.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-patch.t
Labels: package management

#8926 Add a cram alias for the pkg tests
  test/blackbox-tests/test-cases/pkg/dune
  test/expect-tests/dune_pkg/dune
Labels: package management

#8804 refactor: improve sandbox deletion errors
  src/dune_engine/sandbox.ml
  test/blackbox-tests/test-cases/interfere-sandbox-deletion.t
Labels: upstream-sync

#7611 test: `(include_subdirs)` qualified and unqualified and nested menhir
  test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/bar/baz.mly
  test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/bar/dune
  test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/dune-project
  test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/foo.ml
  test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/run.t
Labels: bug, menhir

#8954 doc: document DUNE_CACHE_ROOT in the manpages
  bin/common.ml
Labels: docs

#8920 fix: make copying sandbox files writeable
  doc/changes/8920.md
  src/dune_engine/sandbox.ml
  test/blackbox-tests/test-cases/directory-targets/copy-sandboxing.t
  test/blackbox-tests/test-cases/sandboxing-stale-directory-target.t
Labels: upstream-sync

#8841 feature(pkg): dune describe pkg lock
  bin/describe/describe.ml
  bin/describe/describe_pkg.ml
  bin/describe/describe_pkg.mli
  bin/pkg.ml
  bin/pkg.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
Labels: package management

#8750 test(pkg): show precedence of make and gmake
  test/blackbox-tests/test-cases/pkg/opam-var/make-over-gmake.t
Labels: package management

#8959 pkg: improve dune pkg lock message
  bin/describe/describe_pkg.ml
  bin/pkg.ml
  bin/pkg.mli
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
  test/blackbox-tests/test-cases/pkg/detect-duplicate-lock-dir-paths.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-per-context.t/run.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/multiple-opam-repos.t
  test/blackbox-tests/test-cases/pkg/opam-generate-ocaml-package.t
  test/blackbox-tests/test-cases/pkg/opam-package-copy-files.t
  test/blackbox-tests/test-cases/pkg/opam-package-install-no-build.t
  test/blackbox-tests/test-cases/pkg/opam-package-subst-patch.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-build-env-no-build.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-build-env.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-build-test-and-build-doc.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-extra-source.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-patch-filter.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-patch-multiple.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-patch.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-setenv.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-subst.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
  test/blackbox-tests/test-cases/pkg/opam-source-conversion.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-global.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-os.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-pkg.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-switch.t
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/blackbox-tests/test-cases/pkg/run-converted-opam-commands.t
  test/blackbox-tests/test-cases/pkg/solver-flags-per-context.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#8823 test(pkg): cycles in opam repo
  test/blackbox-tests/test-cases/pkg/opam-package-cycle-with-or.t
  test/blackbox-tests/test-cases/pkg/opam-package-cycle.t
Labels: package management

#8943 chore: improve error message for temp dir failure
  otherlibs/stdune/src/temp.ml
Labels: upstream-sync

#8934 Remove flags from solver_env
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/solver-flags-per-context.t
Labels: package management

#8940 feature: allow custom actions to be dynamic
  src/dune_engine/action_exec.ml
  src/dune_engine/action_intf.ml
Labels: upstream-sync

#8932 feature(engine): allow customizing execution parameters per context
  src/dune_engine/build_config.ml
  src/dune_engine/build_config_intf.ml
  src/dune_engine/build_system.ml
  src/dune_rules/main.ml
Labels: upstream-sync

#8923 fix(pkg): require copying sandbox for build rules
  src/dune_rules/pkg_rules.ml
Labels: package management

#8935 Refactor solver workspace fields
  bin/pkg.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_rules/context.ml
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/multiple-opam-repos.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#8972 fix(engine): remove context from action digest
  bin/print_rules.ml
  src/dune_engine/build_config.ml
  src/dune_engine/build_config_intf.ml
  src/dune_engine/build_context.ml
  src/dune_engine/build_context.mli
  src/dune_engine/build_system.ml
  src/dune_engine/load_rules.ml
  src/dune_engine/reflection.ml
  src/dune_engine/reflection.mli
  src/dune_engine/rule.ml
  src/dune_engine/rule.mli
  src/dune_engine/rules.ml
  src/dune_engine/rules.mli
  src/dune_rules/artifact_substitution.ml
  src/dune_rules/artifact_substitution.mli
  src/dune_rules/configurator_rules.ml
  src/dune_rules/install_rules.ml
  src/dune_rules/main.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/super_context.ml
  test/blackbox-tests/test-cases/dune-cache/mode-copy.t
  test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
  test/blackbox-tests/test-cases/dune-cache/repro-check.t
  test/blackbox-tests/test-cases/dune-cache/trim.t
  test/blackbox-tests/test-cases/patch-back-source-tree.t
Labels: upstream-sync

#8992 melange: remove ppx flag from merlin
  src/dune_rules/merlin/merlin.ml
  test/blackbox-tests/test-cases/melange/merlin.t
  test/expect-tests/persistent_tests.ml
Labels: melange

#8966 fix: failing coq --config
  doc/changes/coq_config_fix.md
  src/dune_rules/coq/coq_config.ml
  src/dune_rules/coq/coq_config.mli
  src/dune_rules/coq/coq_path.ml
  src/dune_rules/coq/coq_rules.ml
  src/dune_rules/expander.ml
  test/blackbox-tests/test-cases/coq/failed-config.t/dune-project
  test/blackbox-tests/test-cases/coq/failed-config.t/run.t
Labels: coq

#8973 pkg: store solver variables in lockdir metadata
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#9035 test(pkg): file-depends
  test/blackbox-tests/test-cases/pkg/file-depends.t
Labels: package management

#9011 chore(pkg): cleanup imports
  src/dune_pkg/fetch.ml
  src/dune_pkg/fetch.mli
  src/dune_pkg/import.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/package_variable.ml
  src/dune_pkg/package_variable.mli
  src/dune_pkg/repository_id.ml
  src/dune_pkg/repository_id.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_pkg/substs.ml
  src/dune_pkg/substs.mli
  src/dune_pkg/sys_poll.ml
  src/dune_pkg/sys_poll.mli
  src/dune_pkg/workspace.ml
Labels: package management

#9037 refactor(pkg): deforest rule/aliases collection
  src/dune_engine/rules.ml
Labels: upstream-sync

#8990 fix: include expand aliases in digest
  doc/changes/8990.md
  src/dune_engine/build_system.ml
  test/blackbox-tests/test-cases/depend-on/expand-aliases-rerun.t
  test/blackbox-tests/test-cases/dune-cache/mode-copy.t
  test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
  test/blackbox-tests/test-cases/dune-cache/repro-check.t
  test/blackbox-tests/test-cases/dune-cache/trim.t
Labels: upstream-sync

#9041 fix: allow internal dune actions to be sandboxed
  doc/changes/9041.md
  src/dune_engine/action.ml
  src/dune_engine/action.mli
  src/dune_engine/build_system.ml
  test/blackbox-tests/test-cases/corrections.t
  test/blackbox-tests/test-cases/sandboxing.t
Labels: upstream-sync

#9058 refactor: drop [~distribute] in [is_useful_to]
  src/dune_engine/action.ml
  src/dune_engine/action_intf.ml
  src/dune_patch/dune_patch.ml
  src/dune_rules/copy_line_directive.ml
  src/dune_rules/cram/cram_exec.ml
  src/dune_rules/format_rules.ml
  src/dune_rules/install_rules.ml
  src/dune_rules/pkg_rules.ml
Labels: upstream-sync
