Repository ocaml/dune, pull requests merged in 2024-06, with the labels that each got.

#10642 pkg: respect avoid-versions between versions of pkg
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/solve-compiler-dependency.t
Labels: package management

#10654 refactor(pkg): remove some unused code
  vendor/opam-0install/lib/dir_context.ml
  vendor/opam-0install/lib/dir_context.mli
  vendor/opam-0install/lib/dune
  vendor/opam-0install/lib/switch_context.ml
  vendor/opam-0install/lib/switch_context.mli
  vendor/update-opam-0install.sh
Labels: package management

#10657 fix(test): correctly scrub coq and coq/theories
  test/blackbox-tests/test-cases/coq/compose-installed-compat.t/run.t
  test/blackbox-tests/test-cases/coq/scrub_coq_args.sh
Labels: test-suite

#10594 pkg: test exercising package disjunctions
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
Labels: package management

#10637 doc: add units to Scheduler.sleep doc
  bin/exec.ml
  bin/monitor.ml
  bin/rpc/build.ml
  src/dune_engine/scheduler.ml
  src/dune_engine/scheduler.mli
  src/dune_pkg/rev_store.ml
  test/expect-tests/dune_patch/dune_patch_tests.ml
  test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
  test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
  test/expect-tests/scheduler_tests.ml
  test/expect-tests/timer_tests.ml
Labels: docs

#10672 pkg: repro for gh10670
  test/blackbox-tests/test-cases/pkg/gh10670.t
Labels: package management

#10631 [coq] make expand "coq.version" and co not depend on coq-stdlib
  doc/changes/10631.md
  src/dune_rules/coq/coq_config.ml
  src/dune_rules/coq/coq_config.mli
  test/blackbox-tests/test-cases/coq/failed-config.t/run.t
Labels: coq

#10489 Fix partial-match warnings
  vendor/opam/src/format/opamTypes.mli
  vendor/opam/src/repository/opamHTTP.ml
  vendor/opam/src/repository/opamRepository.ml
Labels: package management
