Repository ocaml/dune, pull requests merged in 2024-08, with the labels that each got.

#10660 ci: use nix for coq job
  .github/workflows/workflow.yml
  flake.nix
Labels: coq

#10791 Fix some issues with extra-sources
  src/dune_rules/pkg_rules.ml
Labels: package management

#10790 Add repro for gh10788
  test/blackbox-tests/test-cases/pkg/exclusively-extra-sources.t
  test/blackbox-tests/test-cases/pkg/extra-source-overlap-with-source.t
Labels: package management

#10711 docs: "developing with dune" tutorial
  doc/conf.py
  doc/dune
  doc/overview.rst
  doc/requirements.txt
  doc/tutorials/developing-with-dune/conclusion.md
  doc/tutorials/developing-with-dune/development-cycle.md
  doc/tutorials/developing-with-dune/development-cycle/lib/ast.ml
  doc/tutorials/developing-with-dune/development-cycle/lib/cli.ml
  doc/tutorials/developing-with-dune/development-cycle/lib/lexer.mll
  doc/tutorials/developing-with-dune/development-cycle/lib/parser.mly
  doc/tutorials/developing-with-dune/development-cycle/test/calc.t
  doc/tutorials/developing-with-dune/index.md
  doc/tutorials/developing-with-dune/interfacing-with-c.md
  doc/tutorials/developing-with-dune/interfacing-with-c/lib/calc_stubs.c
  doc/tutorials/developing-with-dune/interfacing-with-c/lib/cli.ml
  doc/tutorials/developing-with-dune/interfacing-with-c/lib/dune
  doc/tutorials/developing-with-dune/interfacing-with-c/lib/lexer.mll
  doc/tutorials/developing-with-dune/interfacing-with-c/test/calc.t
  doc/tutorials/developing-with-dune/introduction.md
  doc/tutorials/developing-with-dune/introduction/ast.ml
  doc/tutorials/developing-with-dune/introduction/calc.ml
  doc/tutorials/developing-with-dune/introduction/dune
  doc/tutorials/developing-with-dune/introduction/dune-project
  doc/tutorials/developing-with-dune/introduction/lexer.mll
  doc/tutorials/developing-with-dune/introduction/parser.mly
  doc/tutorials/developing-with-dune/structure.md
  doc/tutorials/developing-with-dune/structure/bin/calc.ml
  doc/tutorials/developing-with-dune/structure/bin/dune
  doc/tutorials/developing-with-dune/structure/lib/cli.ml
  doc/tutorials/developing-with-dune/structure/lib/dune
  doc/tutorials/developing-with-dune/structure/test/calc.t
  doc/tutorials/developing-with-dune/structure/test/dune
  doc/tutorials/developing-with-dune/unit-tests.md
  doc/tutorials/developing-with-dune/using-ppx.md
  doc/tutorials/developing-with-dune/using-ppx/lib/ast.ml
  doc/tutorials/developing-with-dune/using-ppx/lib/cli.ml
  doc/tutorials/developing-with-dune/using-ppx/lib/dune
  doc/tutorials/developing-with-dune/using-ppx/test/calc.t
  flake.nix
Labels: docs

#10777 Jsoo: make dune aware of sourcemap generation
  doc/changes/10777.md
  doc/jsoo.rst
  doc/reference/dune/env.rst
  doc/reference/dune/executable.rst
  src/dune_rules/jsoo/js_of_ocaml.ml
  src/dune_rules/jsoo/js_of_ocaml.mli
  src/dune_rules/jsoo/jsoo_rules.ml
  src/dune_rules/stanzas/buildable.ml
  test/blackbox-tests/test-cases/jsoo/env.t
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/bin/dune
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/bin/main.ml
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/dune-project
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/lib/dune
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/lib/mylib.ml
  test/blackbox-tests/test-cases/jsoo/sourcemap.t/run.t
Labels: jsoo

#10801 Set `Clflags.concurrency` for non watch builds
  bin/import.ml
Labels: package management

#10808 Replace `oneshot_webserver` with fake curl
  src/dune_pkg/fetch.ml
  test/blackbox-tests/test-cases/dune
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/e2e.t
  test/blackbox-tests/test-cases/pkg/extra-sources.t
  test/blackbox-tests/test-cases/pkg/source-caching.t
  test/blackbox-tests/test-cases/pkg/tarball.t
  test/blackbox-tests/test-cases/pkg/unavailable-package-source.t
  test/blackbox-tests/utils/curl
  test/blackbox-tests/utils/dune
  test/blackbox-tests/utils/webserver_oneshot.ml
Labels: package management

#10798 Add test of the toolchains mechanism
  test/blackbox-tests/test-cases/pkg/toolchain-installation.t
Labels: package management

#10810 Use [Config.Toggle] for toolchains
  src/dune_config/config.ml
  src/dune_config/config.mli
  src/dune_rules/pkg_toolchain.ml
  test/blackbox-tests/test-cases/pkg/toolchain-installation.t
Labels: package management

#10816 refactor(pkg): move [variables] to [Dune_pkg]
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#10802 Progress indication for lockdir generation
  bin/pkg/lock.ml
  src/dune_pkg/workspace.mli
Labels: package management

#10815 refactor(pkg): remove some dead code
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: package management

#10814 fix(pkg): do not lock unreachable packages
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/compiler-post-dependencies.t
  test/blackbox-tests/test-cases/pkg/post-deps-solving.t
Labels: package management

#10803 Print package build progress status messages
  src/dune_rules/pkg_build_progress.ml
  src/dune_rules/pkg_build_progress.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#10836 pkg: improve readability of progress messages
  src/dune_rules/pkg_build_progress.ml
Labels: package management

#10843 feat: Adding configure-time toggles
  boot/configure.ml
  src/dune_rules/compile_time.ml
  src/dune_rules/compile_time.mli
  src/dune_rules/pkg_build_progress.ml
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/setup.defaults.ml
  src/dune_rules/setup.mli
Labels: package management

#10847 Return [result] when loading lockdir
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#10853 Typo in preprocessing-spec.rst
  doc/reference/preprocessing-spec.rst
Labels: docs

#10850 feat(pkg): Enable cache on fetch actions
  src/dune_rules/fetch_rules.ml
  test/blackbox-tests/test-cases/pkg/fetch-cache.t
Labels: package management
