Repository ocaml/dune, pull requests merged in 2024-02, with the labels that each got.

#9874 test: repro case for #9873 (directory symlink)
  test/blackbox-tests/test-cases/directory-targets/symlink-dir.t
Labels: package management

#9864 doc: recycle toplevel-integration.rst
  doc/howto/index.rst
  doc/howto/toplevel.rst
  doc/toplevel-integration.rst
Labels: docs

#9798 feature(pkg): Submodule support
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/git_config_parser.ml
  src/dune_pkg/git_config_parser.mli
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/expect-tests/dune_pkg/git_config.ml
Labels: package management

#9920 pkg: test reproducing gh9919
  test/blackbox-tests/test-cases/pkg/absolute-paths-in-sections.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
Labels: package management

#9910 fix(pkg): filter ls-remote
  src/dune_pkg/rev_store.ml
Labels: package management

#9829 doc: explain the bootstrap process
  doc/explanation/bootstrap.rst
  doc/explanation/index.rst
  doc/hacking.rst
Labels: docs

#9905 chore(pkg): Remove rudimentary git config parser in favor of `git config`
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/git_config_parser.ml
  src/dune_pkg/git_config_parser.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/expect-tests/dune_pkg/git_config.ml
Labels: package management

#9865 doc: the Dune Mental Model
  doc/explanation/index.rst
  doc/explanation/mental-model.rst
Labels: docs

#9942 pkg: fix test that would fail on non-amd64
  test/blackbox-tests/test-cases/pkg/lock-directory-selection.t
Labels: package management

#9772 odoc: sherlodoc integration
  doc/changes/9772.md
  doc/documentation.rst
  src/dune_rules/odoc.ml
  src/dune_rules/odoc_new.ml
  src/dune_rules/sherlodoc.ml
  src/dune_rules/sherlodoc.mli
  test/blackbox-tests/test-cases/dune
  test/blackbox-tests/test-cases/invalid-opam-file-name-github8281.t
  test/blackbox-tests/test-cases/odoc/doc-browser.t/foo.ml
  test/blackbox-tests/test-cases/odoc/dune
  test/blackbox-tests/test-cases/odoc/github1645.t
  test/blackbox-tests/test-cases/odoc/multiple-private-libs.t/run.t
  test/blackbox-tests/test-cases/odoc/new/odoc-unique-mlds/diff-scope.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/bar.ml
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/bar.opam
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/dune
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/dune-project
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/foo.ml
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/foo.opam
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/foo2.ml
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/foo3.ml
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/foo_byte.ml
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/bar.ml
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/bar.opam
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/dune
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/dune-project
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/foo.ml
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/foo.opam
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/foo2.ml
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/foo3.ml
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/foo_byte.ml
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-no-sherlodoc.t/test.mld
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/bar.ml
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/bar.opam
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/dune
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/dune-project
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/foo.ml
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/foo.opam
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/foo2.ml
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/foo3.ml
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/foo_byte.ml
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/test.mld
  test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/diff-scope.t/run.t
  test/blackbox-tests/utils/dune
  test/blackbox-tests/utils/sherlodoc.ml
Labels: odoc

#9940 pkg: fix bug preventing paths from being sandboxed
  otherlibs/stdune/src/list.ml
  otherlibs/stdune/src/list.mli
  otherlibs/stdune/test/list_tests.ml
  src/dune_lang/ordered_set_lang_intf.ml
  src/dune_lang/string_with_vars.ml
  src/dune_lang/string_with_vars.mli
  src/dune_lang/value.ml
  src/dune_lang/value.mli
  src/dune_rules/expander.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/slang_expand.ml
  src/dune_rules/slang_expand.mli
  test/blackbox-tests/test-cases/pkg/absolute-paths-in-sections.t
Labels: package management

#9951 refactor(pkg): improve source fetching
  src/dune_pkg/fetch.ml
Labels: package management

#9845 fix(coq): delay boot type detection
  doc/changes/9845.md
  src/dune_rules/coq/coq_rules.ml
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/README.md
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/Common/Foo.v
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/Common/dune
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/_CoqProject
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/dune
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/extracted/CRelationClasses.mli.patch
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/extracted/Extract.v
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/extracted/dune
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/coq/extracted/patch.sh
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/dune
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/dune-project
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/example-coq.opam
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/example-ocaml.opam
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/ml/bar.ml
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/ml/dune
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/run.t
  test/blackbox-tests/test-cases/coq/failed-config.t/run.t
Labels: coq

#9974 test(pkg): dune build command when pinning
  test/blackbox-tests/test-cases/pkg/pin-stanza/opam-template.t
Labels: package management

#9932 fix(pkg): do not redownload the same url's
  otherlibs/stdune/src/fpath.ml
  otherlibs/stdune/src/fpath.mli
  src/dune_pkg/checksum.ml
  src/dune_pkg/checksum.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/fetch_rules.mli
  src/dune_rules/gen_rules.ml
  src/dune_rules/main.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/source-caching.t
Labels: package management

#9973 pkg: test reproducing gh9972
  test/blackbox-tests/test-cases/pkg/additional-constraints-ocaml-system.t
Labels: package management

#9999 pkg: fix applying additional constraints to disjunction
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/additional-constraints-ocaml-system.t
Labels: package management

#9975 feature(pkg): proper build instructions for dune packages
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/pin_stanza.ml
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/pin-stanza/basic.t
  test/blackbox-tests/test-cases/pkg/pin-stanza/build-command-dune-project.t
  test/blackbox-tests/test-cases/pkg/pin-stanza/mixed-opam-dune.t
  test/blackbox-tests/test-cases/pkg/pin-stanza/opam-template.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#10000 pkg: module to convert opam types to `Dyn.t`
  src/dune_pkg/opam_dyn.ml
  src/dune_pkg/opam_dyn.mli
Labels: package management

#10021 pkg: update stale comment in test
  test/blackbox-tests/test-cases/pkg/additional-constraints-ocaml-system.t
Labels: package management

#9956 favour odocls that are not dependencies
  src/dune_rules/odoc.ml
  src/dune_rules/odoc_new.ml
  src/dune_rules/sherlodoc.ml
  src/dune_rules/sherlodoc.mli
  test/blackbox-tests/test-cases/odoc/new/odoc-unique-mlds/diff-scope.t/run.t
  test/blackbox-tests/test-cases/odoc/new/warnings.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/run.t
  test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/run.t
  test/blackbox-tests/utils/sherlodoc.ml
Labels: odoc

#10033 pkg: refactor `available_cache` to be `Table.t`
  src/dune_pkg/opam_solver.ml
Labels: package management

#10045 test(pkg): external lock directory
  test/blackbox-tests/test-cases/pkg/external-lock-dir.t
Labels: package management

#10050 refactor(melange): tighten / remove a few `open` expressions
  src/dune_rules/melange/melange_rules.ml
Labels: melange

#10034 pkg: add cache of asyncronously-computed values
  src/dune_pkg/fiber_cache.ml
  src/dune_pkg/fiber_cache.mli
  src/dune_pkg/opam_solver.ml
Labels: package management

#10053 pkg: back single_run_file_cache with fiber_cache
  src/dune_pkg/single_run_file_cache.ml
  src/dune_pkg/single_run_file_cache.mli
Labels: package management

#10062 test(pkg): initialize mock repo in test
  test/blackbox-tests/test-cases/pkg/pin-stanza/build-command-dune-project.t
Labels: package management

#10051 fix(melange): depend on selected impl when setting up JS rules for virtual lib
  Makefile
  ci/build-test.sh
  doc/changes/10051.md
  flake.lock
  flake.nix
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/private-lib-dep.t
  test/blackbox-tests/test-cases/melange/virtual_lib_compilation.t/dune
  test/blackbox-tests/test-cases/melange/virtual_lib_compilation.t/mel.ml
  test/blackbox-tests/test-cases/melange/virtual_lib_compilation.t/run.t
Labels: melange

#10020 pkg: test when PATH contians a different dune
  test/blackbox-tests/test-cases/pkg/different-dune-in-path.t
Labels: package management

#10069 pkg: use `Fiber_cache.t` for pin traversed cache
  src/dune_pkg/pin_stanza.ml
Labels: package management

#10064 refactor(pkg): remove [Remote.equal]
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
Labels: package management

#10065 refactor(pkg): remove [At_rev.opam_url]
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
Labels: package management

#10066 refactor(pkg): fetch with --no-write-fetch-head
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: package management

#10060 fix: checking out git repos via rev_store
  src/dune_pkg/rev_store.ml
Labels: package management

#10059 test(pkg): modifying default branch
  test/blackbox-tests/test-cases/pkg/default-git-branch.t
Labels: package management

#10075 fix(pkg): do not encode url/checksum locations in action digests
  src/dune_rules/fetch_rules.ml
Labels: package management

#10078 fix(nix): override mdx's propagatedBuildInputs to avoid logs conflicts
  flake.lock
  flake.nix
Labels: nix

#10079 chore(nix): provide a `dune` binary in the scope shell too
  flake.nix
Labels: nix

#10085 fix(pkg): stop using opam's untar code
  src/dune_pkg/fetch.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/tar.ml
  src/dune_pkg/tar.mli
  test/blackbox-tests/test-cases/pkg/e2e.t
Labels: package management

#9712 refactor: optimize [Fpath.is_root]
  otherlibs/stdune/src/fpath.ml
Labels: upstream-sync

#10096 chore(nix): use ocaml-lsp from the provided overlay
  flake.lock
  flake.nix
Labels: nix

#10097 chore(nix): update flakes, use upstream mdx/logs fix
  flake.lock
  flake.nix
Labels: nix

#10102 fix(pkg): workaround for libraries not being found
  src/fs/fs.ml
Labels: package management

#10112 fix(pkg): [Lib.is_local] should handle dune installed packages
  src/dune_rules/lib.ml
  src/dune_rules/lib.mli
Labels: package management

#10086 test(pkg): Test resolution of ambiguous hashes
  test/blackbox-tests/test-cases/pkg/commit-hash-references.t
Labels: package management

#10115 fix(coq): Fix performance regression in coqdep unescaping
  doc/changes/10115.md
  src/dune_rules/coq/coq_rules.ml
Labels: coq

#10103 fix(pkg): correctly set [OCAMLPATH] for context
  src/dune_rules/context.ml
  src/dune_rules/findlib.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_rules.mli
Labels: package management

#10116 [coq] Memoize coqdep parsing
  doc/changes/10116.md
  src/dune_rules/coq/coq_rules.ml
Labels: coq, performance

#10071 fix(pkg): rev store improvements
  bin/pkg/pkg_common.ml
  src/dune_pkg/fetch.ml
  src/dune_pkg/fetch.mli
  src/dune_pkg/mount.ml
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/blackbox-tests/test-cases/pkg/commit-hash-references.t
  test/blackbox-tests/test-cases/pkg/unavailable-package-source.t
  test/expect-tests/dune_pkg/fetch_tests.ml
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: package management

#10130 test(pkg): Extend the test to use recursive submodules
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/submodules.t
Labels: package management

#10140 test(pkg): tarball with/without root dir
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/tarball.t
Labels: package management

#10133 fix(pkg): do not try to compute checksums of vcs pins
  src/dune_pkg/source.ml
Labels: package management

#10132 test(pkg): pinning archives
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#10147 test(pkg): debug tarball test
  test/blackbox-tests/test-cases/pkg/tarball.t
  test/blackbox-tests/utils/webserver_oneshot.ml
Labels: package management

#10156 pkg: add test for different hashing algos
  test/blackbox-tests/test-cases/pkg/hash-algos.t
Labels: package management

#10153 doc: fix example in dynamic-include
  doc/reference/files/dune/dynamic_include.rst
Labels: docs

#10122 fix(pkg): correctly extract tarballs
  src/dune_pkg/fetch.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/tar.ml
  src/dune_pkg/tar.mli
  test/blackbox-tests/test-cases/pkg/e2e.t
  test/blackbox-tests/test-cases/pkg/tarball.t
  test/expect-tests/dune_pkg/dune
  test/expect-tests/dune_pkg/fetch_tests.ml
  test/expect-tests/dune_pkg/tar-inputs/file2.md
  test/expect-tests/dune_pkg/tar-inputs/plaintext.md
Labels: package management

#10131 fix(pkg): correctly rebuild packages when default branch changes
  src/dune_pkg/fetch.ml
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/opam_repo.ml
  src/dune_rules/fetch_rules.ml
  test/blackbox-tests/test-cases/pkg/default-git-branch.t
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: package management
