Repository ocaml/dune, pull requests merged in 2024-05, with the labels that each got.

#10472 test: show crash when defining a context named "install"
  test/blackbox-tests/test-cases/workspaces/custom-context-names.t
Labels: test-suite

#10468 fix(test): silence duplicate -lc++ warnings on mac
  test/blackbox-tests/test-cases/cxx-flags.t/dune
Labels: test-suite, macos

#10482 ci: bump the OCaml trunk version
  .github/workflows/workflow.yml
Labels: test-suite

#10324 merlin: add new contexts commands
  bin/describe/describe.ml
  bin/describe/describe_contexts.ml
  bin/describe/describe_contexts.mli
  bin/ocaml/ocaml_merlin.ml
  doc/changes/10324.md
  doc/reference/dune-workspace/context.rst
  src/dune_rules/context.ml
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/describe/describe-contexts.t
  test/blackbox-tests/test-cases/merlin/alt-context.t
  test/blackbox-tests/test-cases/merlin/default-based-context.t/run.t
Labels: merlin

#10481 ci: run build on macOS x86_64 again
  .github/workflows/workflow.yml
Labels: test-suite

#10214 fix(pkg): Create temporary directories on same FS
  src/dune_pkg/fetch.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/tar.ml
  src/dune_pkg/temp_dir.ml
  src/dune_pkg/temp_dir.mli
Labels: package management

#10491 refactor(pkg): keep the files dir in dune_pkg
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#10496 refactor(pkg): remove some copy paste in git source fetching
  src/dune_pkg/mount.ml
  src/dune_pkg/opam_repo.ml
Labels: package management

#10495 doc: js targets & the `@all` alias
  doc/reference/aliases.rst
Labels: docs

#10492 refactor(pkg): type safe fetch without checksum
  src/dune_pkg/fetch.ml
  src/dune_pkg/fetch.mli
  src/dune_pkg/source.ml
Labels: package management

#10506 fix(pkg): tighten validation around url's
  src/dune_pkg/opamUrl0.ml
Labels: package management

#10510 refactor(pkg): use [User_error.ok_exn]
  bin/describe/describe_pkg.ml
  src/dune_pkg/mount.ml
  src/dune_pkg/opam_repo.ml
Labels: package management

#10511 refactor(pkg): small fetch rules simplifications
  src/dune_rules/fetch_rules.ml
Labels: package management

#10516 test: verify checksums of local archives
  test/blackbox-tests/test-cases/pkg/checksum-local-archive.t
Labels: package management

#10498 fix(pkg): do not prompt for passwords with git
  src/dune_pkg/rev_store.ml
Labels: package management

#10512 fix(pkg): remove External_copy
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/source.ml
  src/dune_pkg/source.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/fetch_rules.mli
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/pin-stanza/update-non-dune-local-pin.t
  test/blackbox-tests/test-cases/pkg/unavailable-package-source.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#10494 feat(melange): support lint in `melange.emit`
  src/dune_rules/melange/melange_rules.ml
  src/dune_rules/melange/melange_stanzas.ml
  src/dune_rules/melange/melange_stanzas.mli
  src/dune_rules/stanzas/buildable.ml
  src/dune_rules/stanzas/buildable.mli
  src/dune_rules/stanzas/lint.ml
  src/dune_rules/stanzas/lint.mli
  src/dune_rules/toplevel.ml
  src/dune_rules/utop.ml
  test/blackbox-tests/test-cases/melange/lint.t/correct/dune
  test/blackbox-tests/test-cases/melange/lint.t/correct_static_add/correct_static_add.ml
  test/blackbox-tests/test-cases/melange/lint.t/correct_static_add/dune
  test/blackbox-tests/test-cases/melange/lint.t/dune-project
  test/blackbox-tests/test-cases/melange/lint.t/run.t
Labels: melange

#10500 fix(pkg): read config file on windows
  src/dune_rules/pkg_rules.ml
Labels: package management

#10531 refactor(pkg): unify concrete deps of local package
  src/dune_pkg/package_universe.ml
  test/blackbox-tests/test-cases/pkg/test-only-deps.t
Labels: package management

#10540 pkg: set with-dev-setup opam variable by default
  src/dune_lang/package_variable_name.ml
  src/dune_lang/package_variable_name.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
Labels: package management

#10471 test: show that universal libraries can't share the public_name
  test/blackbox-tests/test-cases/enabled_if/eif-public-name-collision.t
Labels: test-suite

#10543 pkg: test solver on pkg with constraint conjunction
  test/blackbox-tests/test-cases/pkg/constraint-conjunction.t
Labels: package management

#10544 pkg: dedup package names in dependencies
  src/dune_pkg/resolve_opam_formula.ml
  test/blackbox-tests/test-cases/pkg/constraint-conjunction.t
Labels: package management

#10556 pkg: use our unpack code for rsync urls
  src/dune_pkg/fetch.ml
  test/blackbox-tests/test-cases/pkg/checksum-local-archive.t
Labels: package management

#10559 doc: split docs for builtin aliases
  doc/coq.rst
  doc/documentation.rst
  doc/explanation/ocaml-ecosystem.rst
  doc/explanation/opam-integration.rst
  doc/explanation/tour/rule-generation.rst
  doc/melange.rst
  doc/reference/aliases.rst
  doc/reference/aliases/all.rst
  doc/reference/aliases/check.rst
  doc/reference/aliases/default.rst
  doc/reference/aliases/doc-json.rst
  doc/reference/aliases/doc-private.rst
  doc/reference/aliases/doc.rst
  doc/reference/aliases/fmt.rst
  doc/reference/aliases/install.rst
  doc/reference/aliases/lint.rst
  doc/reference/aliases/runtest.rst
  doc/reference/cram.rst
  doc/reference/dune-project/explicit_js_mode.rst
  doc/reference/dune/cram.rst
  doc/usage.rst
Labels: docs

#10555 doc: remove outdated info about variants
  doc/howto/index.rst
  doc/reference/dune/external_variant.rst
  doc/reference/dune/index.rst
  doc/virtual-libraries.rst
Labels: docs

#10561 pkg: disable hg/darcs fetch code
  src/dune_pkg/fetch.ml
Labels: package management

#10562 pkg: use OpamFilename.raw to avoid stat calls
  src/dune_pkg/opam_file.ml
Labels: package management

#10574 chore(pkg): remove pointless channel when writing lock
  src/dune_pkg/rev_store.ml
  src/dune_util/global_lock.mli
Labels: package management

#10595 pkg: test of how the solver chooses compiler packages
  test/blackbox-tests/test-cases/pkg/solve-compiler-dependency.t
Labels: package management

#10547 fix: don't take build lock for `coq top --no-build`
  bin/coq/coqtop.ml
  doc/changes/10547.md
Labels: coq

#10565 Reproduction case to show that installing deps to the stdlib breaks
  test/blackbox-tests/test-cases/pkg/dependency-install-file.t
Labels: package management

#10602 [coq] [fix] Install .glob files
  doc/changes/10602.md
  src/dune_rules/coq/coq_module.ml
  test/blackbox-tests/test-cases/coq/base.t/run.t
  test/blackbox-tests/test-cases/coq/compose-installed-compat.t/run.t
  test/blackbox-tests/test-cases/coq/compose-installed-rebuild.t/run.t
  test/blackbox-tests/test-cases/coq/compose-installed-sub.t/run.t
  test/blackbox-tests/test-cases/coq/compose-installed.t/run.t
  test/blackbox-tests/test-cases/coq/compose-two-scopes.t/run.t
  test/blackbox-tests/test-cases/coq/config-no-coqc.t/run.t
  test/blackbox-tests/test-cases/coq/native-compose.t/run.t
  test/blackbox-tests/test-cases/coq/native-single.t/run.t
  test/blackbox-tests/test-cases/coq/per_file_flags.t/run.t
  test/blackbox-tests/test-cases/coq/public-dep-on-private.t/run.t
  test/blackbox-tests/test-cases/coq/rec-module.t/run.t
  test/blackbox-tests/test-cases/coq/vos-build.t/run.t
Labels: bug, coq

#10586 fix(mdx): link mdx binary with byte_complete
  doc/changes/10586.md
  src/dune_rules/mdx.ml
  test/blackbox-tests/test-cases/mdx-stanza/dune
  test/blackbox-tests/test-cases/mdx-stanza/shared-libraries.t
Labels: mdx
