Repository ocaml/dune, pull requests merged in 2024-07, with the labels that each got.

#10662 pkg: simplify the display logs
  bin/common.ml
  doc/changes/10662.md
  src/dune_rules/clflags.ml
  src/dune_rules/clflags.mli
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/build-package-logs.t
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/pin-stanza/update-non-dune-local-pin.t
Labels: package management

#10690 fix: better grep granularity in pkg test output
  test/blackbox-tests/test-cases/pkg/pin-stanza/update-non-dune-local-pin.t
Labels: test-suite

#10693 Add rule for bc-for-jsoo target only when performing whole program compilation
  src/dune_rules/exe_rules.ml
  src/dune_rules/inline_tests.ml
  src/dune_rules/jsoo/jsoo_rules.mli
  test/blackbox-tests/test-cases/default-targets/bins.t/run.t
  test/blackbox-tests/test-cases/jsoo/explicit-js-mode-specified.t/run.t
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
Labels: jsoo

#10704 fix: setup_alias doc comment remove duplicated "the"
  src/dune_rules/format_rules.mli
Labels: docs

#10705 test: fix oneshot webserver for large binary files
  test/blackbox-tests/utils/webserver_oneshot.ml
  test/http/http.ml
  test/http/http.mli
Labels: package management

#10706 Fix rule target conflict with extra source
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/extra-sources.t
Labels: package management

#10714 tests: Automatically shut down the one-shot server after some time
  test/http/http.ml
Labels: package management

#10668 pkg: workaround to avoid unstable compilers
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
  test/blackbox-tests/test-cases/pkg/solve-compiler-dependency.t
Labels: package management

#10718 doc: split foreign.rst
  doc/concepts/variables.rst
  doc/foreign-code.rst
  doc/reference/dune-project/use_standard_c_and_cxx_flags.rst
  doc/reference/dune/executable.rst
  doc/reference/dune/foreign_library.rst
  doc/reference/dune/library.rst
  doc/reference/extra-objects.rst
  doc/reference/foreign-archives.rst
  doc/reference/foreign-flags.rst
  doc/reference/foreign-stubs.rst
  doc/reference/index.rst
Labels: docs

#10736 test: explicitly use str in multi-context-error.t
  test/blackbox-tests/test-cases/multi-context-error.t
Labels: test-suite

#10740 Add repro of gh10739
  test/blackbox-tests/test-cases/pkg/pin-stanza/pin-depopts.t
Labels: package management

#10752 feature(pkg): set [post = true] when solving
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_universe.ml
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/resolve_opam_formula.mli
  src/dune_pkg/solver_env.ml
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
  test/blackbox-tests/test-cases/pkg/compiler-post-dependencies.t
  test/blackbox-tests/test-cases/pkg/gh10670.t
  test/blackbox-tests/test-cases/pkg/just-print-solver-env.t
  test/blackbox-tests/test-cases/pkg/post-deps-solving.t
Labels: package management

#10753 Revert "test: fix oneshot webserver for large binary files (#10705)"
  test/blackbox-tests/utils/webserver_oneshot.ml
  test/expect-tests/dune_pkg/fetch_tests.ml
  test/http/http.ml
  test/http/http.mli
Labels: test-suite, package management

#10755 fix(pkg): set jobs to -j
  bin/import.ml
  src/dune_rules/clflags.ml
  src/dune_rules/clflags.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#10757 test(menhir): avoid warning 63 on OCaml 5.2
  test/blackbox-tests/test-cases/menhir/library-interface.t
Labels: menhir, test-suite

#10737 test: do not use unix in implicit-transitive-deps
  test/blackbox-tests/test-cases/merlin/implicit-transitive-deps.t/run.t
  test/blackbox-tests/test-cases/merlin/implicit-transitive-deps.t/src/lib2/dune
  test/blackbox-tests/test-cases/merlin/implicit-transitive-deps.t/src/lib2/lib2.ml
  test/blackbox-tests/test-cases/merlin/implicit-transitive-deps.t/src/lib_dep/dep.ml
  test/blackbox-tests/test-cases/merlin/implicit-transitive-deps.t/src/lib_dep/dune
Labels: test-suite

#10760 doc: add an example for variable name :version
  doc/howto/opam-file-generation.rst
Labels: docs

#10754 fix(pkg): pinning depopts
  src/dune_pkg/local_package.ml
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_dependency.mli
  test/blackbox-tests/test-cases/pkg/pin-stanza/pin-depopts.t
Labels: package management

#10761 test(pkg): bring back timeout
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
  test/http/http.ml
Labels: package management

#10759 test(site): cat whole install file
  otherlibs/dune-site/test/run.t
  otherlibs/dune-site/test/run_2_9.t
Labels: test-suite

#10768 refactor(pkg): separate read from write paths
  otherlibs/stdune/src/lazy.ml
  otherlibs/stdune/src/stdune.ml
  src/dune_rules/pkg_rules.ml
  src/install/roots.ml
  src/install/roots.mli
Labels: package management

#10769 feature(pkg): toolchains
  otherlibs/stdune/src/path.ml
  otherlibs/stdune/src/path.mli
  src/dune_rules/dune
  src/dune_rules/ocaml_toolchain.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: package management

#10773 refactor(pkg): simplify some bindings
  src/dune_pkg/opam_solver.ml
Labels: package management

#10772 fix(pkg): better error message for avoid-version: false
  src/dune_pkg/opam_solver.ml
Labels: package management

#10774 fix(pkg): remove dune from lock dir
  src/dune_pkg/dune_dep.ml
  src/dune_pkg/dune_dep.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: package management

#10781 refactor(pkg): add some cookie docs
  src/dune_rules/pkg_rules.ml
Labels: package management

#10782 Create cookie file for toolchain packages
  otherlibs/stdune/src/path.ml
  otherlibs/stdune/src/path.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: package management

#10787 Set install_roots for toolchain packages
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: package management
