Repository ocaml/dune, pull requests merged in 2024-12, with the labels that each got.

#11162 Add some documentation about dune toolchains
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: package management

#11153 feat: ensure `@pkg-install` is not registered without lock file
  doc/reference/aliases/pkg-install.rst
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/describe/aliases.t/run.t
  test/blackbox-tests/test-cases/pkg/alias-pkg-install.t
Labels: package management

#11184 Update Wasm_of_ocaml action
  .github/workflows/workflow.yml
Labels: chore

#11183 Rename `source` to `url` in `repository` stanza
  doc/tutorials/dune-package-management/repos/dune-workspace
  src/dune_pkg/workspace.ml
  test/blackbox-tests/test-cases/pkg/additional-constraints-ocaml-system.t
  test/blackbox-tests/test-cases/pkg/additional-constraints.t
  test/blackbox-tests/test-cases/pkg/commit-hash-references.t
  test/blackbox-tests/test-cases/pkg/describe-pkg-lock.t
  test/blackbox-tests/test-cases/pkg/duplicate-repositories.t
  test/blackbox-tests/test-cases/pkg/env-conditional-dependencies.t
  test/blackbox-tests/test-cases/pkg/git-repo.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
  test/blackbox-tests/test-cases/pkg/invalid-version.t
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
  test/blackbox-tests/test-cases/pkg/lock-directory-selection.t
  test/blackbox-tests/test-cases/pkg/lockdir-tampering.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/multiple-opam-repo-override.t
  test/blackbox-tests/test-cases/pkg/multiple-opam-repos.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/helpers.sh
  test/blackbox-tests/test-cases/pkg/ocamllsp/helpers.sh
  test/blackbox-tests/test-cases/pkg/odoc/helpers.sh
  test/blackbox-tests/test-cases/pkg/opam-only-metadata.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/outdated.t
  test/blackbox-tests/test-cases/pkg/partial-filter-evaluation.t
  test/blackbox-tests/test-cases/pkg/pin-stanza/workspace.t
  test/blackbox-tests/test-cases/pkg/pkg-validate-on-build.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock-linux.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock.t
  test/blackbox-tests/test-cases/pkg/solve-lockdir-without-context.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
  test/blackbox-tests/test-cases/pkg/submodules.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#11185 Simplify addition of mock-repo in a lot of tests
  test/blackbox-tests/test-cases/pkg/commit-hash-references.t
  test/blackbox-tests/test-cases/pkg/git-repo.t
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
  test/blackbox-tests/test-cases/pkg/invalid-version.t
  test/blackbox-tests/test-cases/pkg/lockdir-tampering.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock-linux.t
  test/blackbox-tests/test-cases/pkg/rev-store-lock.t
  test/blackbox-tests/test-cases/pkg/submodules.t
Labels: package management

#11186 Rename sources into pins
  bin/lock_dev_tool.ml
  bin/pkg/lock.ml
  bin/pkg/lock.mli
  src/dune_rules/dune_project.ml
  src/dune_rules/dune_project.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
Labels: package management

#11187 Add pins of dune-project to Dyn representation
  src/dune_rules/dune_project.ml
Labels: package management

#11195 Better doc for `(no_dynlink)`
  doc/reference/dune/library.rst
Labels: docs

#11189 [3.17] `(no_dynlink)`: do not build `.cmxs` (#11176)
  doc/changes/11176.md
  src/dune_rules/lib_info.ml
  src/dune_rules/lib_info.mli
  src/dune_rules/lib_rules.ml
  test/blackbox-tests/test-cases/no_dynlink.t
  test/blackbox-tests/test-cases/pkg/ignored-dune-lock.t
Labels: release

#11218 [3.17] `Io.copy_channels`: make it reentrant (#11194)
  doc/changes/11194.md
  otherlibs/stdune/src/io.ml
  otherlibs/stdune/src/io.mli
Labels: release

#11216 [3.17] backport 11204 - remove errors message from `dune subst` with empty dir
  bin/subst.ml
  doc/changes/11204.md
  test/blackbox-tests/test-cases/github11200.t
Labels: release

#11221 chore: prepare 3.17.1 changelog
  CHANGES.md
  doc/changes/11176.md
  doc/changes/11194.md
  doc/changes/11204.md
Labels: release

#11224 chore(ci): remove coveralls
  .github/workflows/workflow.yml
Labels: chore

#11206 refactor(melange): don't store `dune_version` in `Melange_stanzas.Emit.t`
  src/dune_rules/melange/melange_stanzas.ml
  src/dune_rules/melange/melange_stanzas.mli
  src/dune_rules/ml_sources.ml
Labels: melange

#11211 test(melange): use a different flag for forwards-compat
  test/blackbox-tests/test-cases/melange/merlin.t
Labels: test-suite, melange

#11207 refactor(melange): don't run `Lib.Compile.requires_link` twice
  src/dune_rules/melange/melange_rules.ml
Labels: melange

#11230 chore: changelog 3.17.1
  CHANGES.md
  doc/changes/11176.md
  doc/changes/11194.md
  doc/changes/11204.md
Labels: release

#11223 refactor(pkg): remove [`Recommended] dep importance
  src/0install-solver/s.ml
  src/0install-solver/solver_core.ml
  src/opam-0install/lib/model.ml
Labels: package management

#11233 refactor(pkg): remove replaced-by remnants
  src/0install-solver/diagnostics.ml
  src/0install-solver/s.ml
  src/0install-solver/solver_core.ml
  src/opam-0install/lib/model.ml
Labels: package management

#11234 feat(dune): support `+` prefixes for PPX CLI flags
  src/dune_rules/preprocess.ml
  test/blackbox-tests/test-cases/ppx/ppx-flags-plus.t
Labels: enhancement

#11248 fix(melange): use output of virtual library when compiling its source
  doc/changes/11248.md
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/virtual-lib-public-impl.t
Labels: melange

#11197 Better error message for old versions of Git
  src/dune_pkg/dune
  src/dune_pkg/rev_store.ml
Labels: package management
