Repository ocaml/dune, pull requests merged in 2024-10, with the labels that each got.

#10980 test(pkg): repro 10839
  src/dune_rules/dune_file.ml
  test/blackbox-tests/test-cases/pkg/ocaml-syntax-gh10839.t
Labels: package management

#10975 Minor changes to package management tutorial
  doc/tutorials/dune-package-management/dependencies.md
  doc/tutorials/dune-package-management/pinning.md
  doc/tutorials/dune-package-management/repos.md
  doc/tutorials/dune-package-management/setup.md
Labels: docs, package management

#10947 test(pkg): reproduce not finding the patch file (`dune fmt`)
  test/blackbox-tests/test-cases/pkg/ocamlformat/dune
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-patch-extra-files.t
Labels: package management

#10981 flake: add dep on myst-parser to docInputs
  flake.nix
Labels: nix

#10950 doc(pkg): Explain package management
  doc/explanation/index.rst
  doc/explanation/package-management.md
Labels: docs, package management

#10994 doc: Add version info to the codeberg documentation
  doc/reference/dune-project/generate_opam_files.rst
Labels: docs

#10995 test(pkg): reproduce [@ocaml-index] failing with package management
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/gh10985.t
Labels: package management

#10993 pkg: add repro for gh10991
  test/blackbox-tests/test-cases/pkg/ocamlformat/gh10991.t
Labels: package management

#10998 refactor(pkg): only pass what is necessary to various functions
  src/dune_pkg/package_universe.ml
  src/dune_pkg/package_universe.mli
  src/dune_rules/gen_rules.ml
Labels: package management

#11004 test(pkg): Reproduce depexts message bug
  test/blackbox-tests/test-cases/pkg/depexts/error-message.t
Labels: package management

#11005 fix(pkg): print depexts message when a program is not found
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/depexts/error-message.t
Labels: package management

#10990 pkg: fix dev-tool bug where `dune fmt` would revert file
  src/dune_rules/format_rules.ml
  test/blackbox-tests/test-cases/pkg/ocamlformat/gh10991.t
Labels: package management

#11024 test(pkg): use explicit build targets
  test/blackbox-tests/test-cases/pkg/absolute-paths-in-sections.t
  test/blackbox-tests/test-cases/pkg/different-dune-in-path.t
  test/blackbox-tests/test-cases/pkg/extra-source-overlap-with-source.t
  test/blackbox-tests/test-cases/pkg/fetch-cache.t
  test/blackbox-tests/test-cases/pkg/lock-out-of-sync.t
  test/blackbox-tests/test-cases/pkg/pin-stanza/update-non-dune-local-pin.t
  test/blackbox-tests/test-cases/pkg/toolchain-installation.t
Labels: package management

#11025 fix(pkg): dependency closure should be lazier
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/ocaml-syntax-gh10839.t
Labels: package management

#11026 fix(pkg): allow OCaml syntax in dune files with lock dirs
  src/dune_rules/context.ml
  test/blackbox-tests/test-cases/pkg/ocaml-syntax-gh10839.t
Labels: package management

#10960 test: reproduce `dune exec -w` crash with pkg management
  bin/exec.ml
  test/blackbox-tests/test-cases/pkg/gh10959.t
Labels: package management

#11022 refactor(pkg): simplify depopts handling
  src/dune_pkg/opam_solver.ml
Labels: package management

#11020 pkg: add binary dev tools repo
  bin/lock_dev_tool.ml
  bin/pkg/pkg_common.ml
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/workspace.ml
  src/dune_pkg/workspace.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
Labels: package management

#11035 fix(pkg): do not generate index rules
  src/dune_rules/merlin/ocaml_index.ml
  test/blackbox-tests/test-cases/pkg/gh10985.t
Labels: merlin, package management

#11047 test: add repro for gh11037
  test/blackbox-tests/test-cases/pkg/ocamlformat/gh11037.t
Labels: package management

#11048 refactor: define lock_dev_tools feature flag in dune_rules
  bin/lock_dev_tool.ml
  src/dune_rules/compile_time.ml
  src/dune_rules/compile_time.mli
  src/dune_rules/dune_rules.ml
Labels: package management

#11054 test: forward port cpp test for 4.14.2
  test/blackbox-tests/test-cases/cpp-std-ocaml5.t/cpp11.cpp
  test/blackbox-tests/test-cases/cpp-std-ocaml5.t/run.t
Labels: bug
