Repository ocaml/dune, pull requests merged in 2024-09, with the labels that each got.

#10834 Fix incorrect sentance/wording in `executable` docs
  doc/reference/dune/executable.rst
Labels: docs

#10876 fix: create lock dir parent if missing
  src/dune_pkg/lock_dir.ml
  test/blackbox-tests/test-cases/pkg/lock-directory-regeneration-safety.t/run.t
Labels: bug, package management

#10865 Better patch format parsing
  src/dune_patch/dune_patch.ml
  test/expect-tests/dune_patch/dune_patch_tests.ml
Labels: package management, package management build failures

#10879 test: Spaces in filenames repro case
  test/expect-tests/dune_patch/dune_patch_tests.ml
Labels: package management

#10869 Fix staged pps on Windows
  doc/changes/10869.md
  otherlibs/stdune/src/string.ml
  otherlibs/stdune/src/string.mli
  test/blackbox-tests/test-cases/dune
Labels: windows

#10884 perf: add names to source tree events
  bin/target.ml
  doc/changes/10884.md
  src/dune_rules/alias_rec.ml
  src/dune_rules/dune_load.ml
  src/dune_rules/foreign_rules.ml
  src/dune_rules/source_deps.ml
  src/dune_rules/source_tree.ml
  src/dune_rules/source_tree.mli
  src/dune_rules/utop.ml
  src/upgrader/dune_upgrader.ml
  test/blackbox-tests/test-cases/trace-file.t/run.t
Labels: performance

#10858 feat: create an alias from pkg to package
  bin/main.ml
  bin/pkg/pkg.ml
  bin/pkg/pkg.mli
  doc/dune.inc
Labels: package management

#10887 test: prefix XDG_STATE_HOME
  otherlibs/dune-rpc-lwt/examples/rpc_client/test/rpc-client-example.t/run.t
Labels: test-suite

#10885 Support patches without a prefix by determining the prefix depth
  src/dune_patch/dune_patch.ml
  test/expect-tests/dune_patch/dune_patch_tests.ml
Labels: package management

#10895 test: Repro case for when the patch prefix is not `a/`/`b/`
  test/expect-tests/dune_patch/dune_patch_tests.ml
Labels: package management

#10899 fix: Support prefixes other than `a/` & `b/` when modifying files
  src/dune_patch/dune_patch.ml
  test/expect-tests/dune_patch/dune_patch_tests.ml
Labels: package management

#10897 Fix url opened by "dune ocaml doc"
  bin/ocaml/doc.ml
  doc/changes/10897.md
  test/blackbox-tests/test-cases/odoc/doc-browser.t/run.t
Labels: odoc

#10902 toolchain: Remove locations from pkg before hashing
  src/dune_pkg/lock_dir.mli
  src/dune_rules/pkg_toolchain.ml
Labels: package management

#10901 Allow printing custom build progress messages
  src/dune_rules/pkg_build_progress.ml
  src/dune_rules/pkg_build_progress.mli
Labels: package management

#10647 pkg: build and make ocamlformat dev-tool available
  bin/build_cmd.ml
  bin/lock_dev_tool.ml
  bin/lock_dev_tool.mli
  bin/pkg/lock.ml
  bin/pkg/lock.mli
  boot/configure.ml
  src/dune_pkg/dev_tool.ml
  src/dune_pkg/dev_tool.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/ocamlformat.ml
  src/dune_pkg/ocamlformat.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/format_rules.ml
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_dev_tool.ml
  src/dune_rules/pkg_dev_tool.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/setup.defaults.ml
  src/dune_rules/setup.mli
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/ocamlformat/dune
  test/blackbox-tests/test-cases/pkg/ocamlformat/helpers.sh
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-avoid-conflict-with-project.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-avoid-taking-from-project-deps.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-dev-tool-deps-conflict-project-deps.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-dev-tool-fails-to-build.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-e2e.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-ignore.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-solving-fails.t
Labels: package management

#10908 Fix bug updating lockdir inside subdirectory
  src/dune_pkg/lock_dir.ml
Labels: package management

#10907 pkg: change progress message color
  src/dune_rules/pkg_build_progress.ml
Labels: package management

#10912 Add links between tutorial sections
  doc/index.rst
  doc/tutorials/developing-with-dune/index.md
  doc/tutorials/index.md
Labels: docs

#10917 chore(nix): add dev tool as experimental flags
  flake.nix
Labels: package management

#10851 feat: dune build asks for relocking
  src/dune_pkg/package_universe.ml
  src/dune_pkg/package_universe.mli
  src/dune_rules/gen_rules.ml
  test/blackbox-tests/test-cases/pkg/lock-out-of-sync.t
Labels: package management

#10900 pkg: add support for opam `depexts`
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/depexts/error-message.t
  test/blackbox-tests/test-cases/pkg/depexts/solve.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#10928 refactor(pkg): tweak experimental flag names
  boot/configure.ml
  flake.nix
Labels: package management

#10939 test(pkg): reproduce depext crash
  test/blackbox-tests/test-cases/pkg/depexts/unknown-variable.t
Labels: package management

#10914 Add odoc dev tool
  bin/build_cmd.ml
  bin/lock_dev_tool.ml
  bin/lock_dev_tool.mli
  bin/ocaml/doc.ml
  src/dune_pkg/dev_tool.ml
  src/dune_pkg/dev_tool.mli
  src/dune_rules/dune_rules.ml
  src/dune_rules/fetch_rules.ml
  src/dune_rules/odoc.ml
  test/blackbox-tests/test-cases/pkg/odoc/dev-tool-odoc-basic.t
  test/blackbox-tests/test-cases/pkg/odoc/dev-tool-odoc-no-lock-dir.t
  test/blackbox-tests/test-cases/pkg/odoc/dev-tool-odoc-no-ocaml-lockfile.t
  test/blackbox-tests/test-cases/pkg/odoc/dev-tool-odoc-relock-on-ocaml-version-change.t
  test/blackbox-tests/test-cases/pkg/odoc/dune
  test/blackbox-tests/test-cases/pkg/odoc/helpers.sh
Labels: package management

#10915 Add ocamllsp dev tool
  bin/lock_dev_tool.ml
  bin/lock_dev_tool.mli
  bin/main.ml
  bin/tools/ocamllsp.ml
  bin/tools/ocamllsp.mli
  bin/tools/tools.ml
  bin/tools/tools.mli
  src/dune_pkg/dev_tool.ml
  src/dune_pkg/dev_tool.mli
  src/dune_rules/dune_rules.ml
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-basic.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-no-lock-dir.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-no-ocaml-lockfile.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-outside-dune-project.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-relock-on-ocaml-version-change.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dune
  test/blackbox-tests/test-cases/pkg/ocamllsp/helpers.sh
Labels: package management

#10920 doc: `dune pkg` tutorial
  doc/tutorials/dune-package-management/dependencies.md
  doc/tutorials/dune-package-management/dependencies/constraints
  doc/tutorials/dune-package-management/dependencies/dune
  doc/tutorials/dune-package-management/dependencies/dune-project
  doc/tutorials/dune-package-management/dependencies/test.ml
  doc/tutorials/dune-package-management/index.md
  doc/tutorials/dune-package-management/pinning.md
  doc/tutorials/dune-package-management/pinning/dune-project
  doc/tutorials/dune-package-management/repos.md
  doc/tutorials/dune-package-management/repos/dune-workspace
  doc/tutorials/dune-package-management/setup.md
  doc/tutorials/dune-package-management/setup/dune
  doc/tutorials/dune-package-management/setup/dune-project
  doc/tutorials/dune-package-management/setup/test.ml
  doc/tutorials/index.md
Labels: docs, package management

#10946 Add fake curl exe to ocamlformat tests
  test/blackbox-tests/test-cases/pkg/ocamlformat/dune
Labels: package management

#10935 Pass the linkall flag to jsoo in whole program compilation as well
  doc/changes/10935.md
  src/dune_rules/jsoo/jsoo_rules.ml
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
Labels: jsoo
