Repository ocaml/dune, pull requests merged in 2024-11, with the labels that each got.

#10929 Add command wrapping ocamlformat
  bin/tools/ocamlformat.ml
  bin/tools/ocamlformat.mli
  bin/tools/tools.ml
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-wrapper.t
Labels: package management

#10937 Configurator: pkg-config plugin uses pkgconf and --personality=TARGET by default
  doc/changes/10937.md
  otherlibs/configurator/src/v1.ml
  otherlibs/configurator/src/v1.mli
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/dune
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/pkgconf.ml
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/run.t
  otherlibs/configurator/test/blackbox-tests/pkg-config-quoting.t/pkg_config.ml
  otherlibs/configurator/test/blackbox-tests/pkg-config-quoting.t/run.t
Labels: configurator

#10918 pkg: Use `filtered_formula` to represent dependencies
  bin/describe/describe_pkg.ml
  bin/lock_dev_tool.ml
  src/dune_pkg/dependency_formula.ml
  src/dune_pkg/dependency_formula.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_universe.ml
  src/dune_pkg_outdated/dune_pkg_outdated.ml
  test/blackbox-tests/test-cases/pkg/check-dependency-hash.t
  test/blackbox-tests/test-cases/pkg/common-filters-deps.t
  test/blackbox-tests/test-cases/pkg/dependency-hash.t
  test/blackbox-tests/test-cases/pkg/hash-algos.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-file-errors.t
  test/blackbox-tests/test-cases/pkg/opam-file.t
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
Labels: package management

#11095 Fix before the next jsoo release
  test/blackbox-tests/test-cases/jsoo/no-check-prim.t/lib/runtime.js
  test/blackbox-tests/test-cases/jsoo/simple.t/lib/runtime.js
Labels: jsoo

#11098 test: extend dune-constraint test to reproduce #11096
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: test-suite, package management

#11090 fix(pkg): handle nested [Or] in depopts
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/depopts/gh11058.t
Labels: package management

#11103 fix: Add or remove dune from package sets to allow resolving packages depending on it
  src/dune_pkg/dune_dep.ml
  src/dune_pkg/dune_dep.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: package management

#11094 Add support for `coqdep` flags.
  doc/changes/11094.md
  doc/coq.rst
  src/dune_rules/coq/coq_env.ml
  src/dune_rules/coq/coq_env.mli
  src/dune_rules/coq/coq_flags.ml
  src/dune_rules/coq/coq_flags.mli
  src/dune_rules/coq/coq_rules.ml
  src/dune_rules/coq/coq_stanza.ml
  src/dune_rules/coq/coq_stanza.mli
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/dune-project
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/dune.disabled
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/run.t
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/theories/bar.v
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/theories/dune.flags
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/theories/dune.noflags
  test/blackbox-tests/test-cases/coq/coqdep-flags.t/theories/foo.v
  test/blackbox-tests/test-cases/coq/coqtop/coqtop-root.t/run.t
  test/blackbox-tests/test-cases/coq/github3624.t
  test/blackbox-tests/test-cases/workspaces/workspace-env.t/run.t
Labels: coq

#11115 test: reproduction case for ignored `dune.lock`
  test/blackbox-tests/test-cases/pkg/ignored-dune-lock.t
Labels: package management

#11120 test: Add repro case for #11113
  test/blackbox-tests/test-cases/pkg/pin-stanza/git-source.t
Labels: package management

#11092 Explain how to override default entry point
  doc/howto/index.rst
  doc/howto/override-default-entrypoint.rst
Labels: docs

#11125 Small cleanup in the jsoo rules
  src/dune_rules/jsoo/jsoo_rules.ml
Labels: jsoo

#11124 Js_of_ocaml rules: fix whole program compilation
  src/dune_rules/exe_rules.ml
  src/dune_rules/inline_tests.ml
  src/dune_rules/jsoo/jsoo_rules.ml
  src/dune_rules/jsoo/jsoo_rules.mli
  test/blackbox-tests/test-cases/jsoo/whole_program.t/a.ml
  test/blackbox-tests/test-cases/jsoo/whole_program.t/b.expected
  test/blackbox-tests/test-cases/jsoo/whole_program.t/b.ml
  test/blackbox-tests/test-cases/jsoo/whole_program.t/dune
  test/blackbox-tests/test-cases/jsoo/whole_program.t/dune-project
  test/blackbox-tests/test-cases/jsoo/whole_program.t/run.t
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/a.ml
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/b.expected
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/b.ml
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/dune
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/dune-project
  test/blackbox-tests/test-cases/wasmoo/whole_program.t/run.t
Labels: jsoo

#11127 fix: Don't fail if repo has clashing branch/tag names
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/pin-stanza/git-source.t
Labels: package management

#11126 Transition from Fmt to Pp all around 0install
  boot/libs.ml
  src/0install-solver/diagnostics.ml
  src/0install-solver/dune
  src/0install-solver/s.ml
  src/0install-solver/sat.ml
  src/0install-solver/sat.mli
  src/0install-solver/solver_core.ml
  src/0install-solver/zeroinstall_solver.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/opam-0install/lib/dune
  src/opam-0install/lib/model.ml
  src/opam-0install/lib/s.ml
  src/opam-0install/lib/solver.ml
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-relaxed-version-constraints.t
Labels: package management

#10951 fix(pkg): `dune fmt` missing extra files from the locks.
  bin/fmt.ml
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-patch-extra-files.t
Labels: package management

#11046 feat: introduce the @pkg-install alias
  src/dune_rules/alias0.ml
  src/dune_rules/alias0.mli
  src/dune_rules/gen_rules.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_rules.mli
  test/blackbox-tests/test-cases/pkg/alias-pkg-install.t
Labels: package management

#11040 Drastically simplify output when packages are missing in solve
  src/0install-solver/diagnostics.ml
  src/opam-0install/lib/solver.ml
  test/blackbox-tests/test-cases/pkg/conflict-class.t
  test/blackbox-tests/test-cases/pkg/conflicts.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/non-existent-dep.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-relaxed-version-constraints.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-solving-fails.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#11137 doc: add @pkg-install alias documentation
  doc/reference/aliases.rst
  doc/reference/aliases/pkg-install.rst
  doc/tutorials/dune-package-management/setup.md
Labels: docs

#10932 doc: update dependencies in the doc itself
  doc/hacking.rst
Labels: docs

#11142 test: Add reproduction case for #11140
  test/blackbox-tests/test-cases/pkg/pin-stanza/git-source.t
Labels: package management

#11145 pkg: Print all the depexts
  bin/describe/describe.ml
  bin/describe/describe_depexts.ml
  bin/describe/describe_depexts.mli
  test/blackbox-tests/test-cases/pkg/depexts/print-depexts.t
Labels: package management

#11144 chore: changelog for 3.17.0~alpha0
  CHANGES.md
  doc/changes/10414.md
  doc/changes/10535.md
  doc/changes/10623.md
  doc/changes/10631.md
  doc/changes/10644.md
  doc/changes/10649.md
  doc/changes/10650.md
  doc/changes/10671.md
  doc/changes/10766.md
  doc/changes/10771.md
  doc/changes/10777.md
  doc/changes/10783.md
  doc/changes/10831.md
  doc/changes/10835.md
  doc/changes/10848.md
  doc/changes/10849.md
  doc/changes/10869.md
  doc/changes/10881.md
  doc/changes/10883.md
  doc/changes/10884.md
  doc/changes/10890.md
  doc/changes/10892.md
  doc/changes/10897.md
  doc/changes/10904.md
  doc/changes/10923.md
  doc/changes/10935.md
  doc/changes/10936.md
  doc/changes/10937.md
  doc/changes/10944.md
  doc/changes/10982.md
  doc/changes/11041.md
  doc/changes/11081.md
  doc/changes/11093.md
  doc/changes/11094.md
  doc/changes/11128.md
  doc/changes/11129.md
Labels: release

#11152 [3.17] chore: add alpha0 date
  CHANGES.md
Labels: release

#11165 [3.17] 3.17.0 changelog
  CHANGES.md
Labels: release
