Repository ocaml/dune, pull requests merged in 2024-01, with the labels that each got.

#9561 pkg: store vars in commnad filters in metadata
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/solver-vars-in-lockdir-metadata.t
Labels: package management

#9617 fix(pkg): read default branch correctly
  src/dune_pkg/rev_store.ml
Labels: package management

#9619 test(pkg): test local rev store
  test/blackbox-tests/test-cases/pkg/helpers.sh
Labels: package management

#9616 refactor(pkg): move global rev_store to [Rev_store]
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
Labels: package management

#9620 fix(pkg): improve url validation in repos
  src/dune_pkg/workspace.ml
  src/dune_pkg/workspace.mli
Labels: package management

#9623 refactor(pkg): move repo backend to own module
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/source_backend.ml
  src/dune_pkg/source_backend.mli
Labels: package management

#9624 test(pkg): multiple repo handling
  test/blackbox-tests/test-cases/pkg/multiple-opam-repo-override.t
Labels: package management

#9626 refactor(pkg): make [Resolved_package] more abstract
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
Labels: package management

#9614 refactor(pkg): Remove `Repository_id`
  bin/pkg/lock.ml
  bin/pkg/pkg_common.ml
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/repository_id.ml
  src/dune_pkg/repository_id.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/rev_store.mli
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#9628 fix(pkg): force repos to use git:// prefix for git
  bin/pkg/pkg_common.ml
Labels: package management

#9631 fix(pkg): add url validation to package sources
  src/dune_pkg/source.ml
Labels: package management

#9632 refactor(pkg): move more code to [Resolved_package]
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
Labels: package management

#9606 fix(pkg): include all error messages
  bin/pkg/lock.ml
  otherlibs/stdune/src/result.ml
  otherlibs/stdune/src/result.mli
  test/blackbox-tests/test-cases/pkg/conflict-class.t
  test/blackbox-tests/test-cases/pkg/conflicts.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
  test/blackbox-tests/test-cases/pkg/with-test-dependencies.t
Labels: package management

#9605 fix(pkg): set (dev true) for packages without checksums
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
Labels: package management

#9649 refactor(pkg): improve file io in sys_poll
  src/dune_pkg/sys_poll.ml
Labels: package management

#9642 fix(pkg): pass locations to [Opam_repo.Source] and to command line
  bin/pkg/pkg_common.ml
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/source.ml
  src/dune_pkg/workspace.ml
  src/dune_pkg/workspace.mli
  test/expect-tests/dune_pkg/fetch_tests.ml
  test/expect-tests/dune_pkg/rev_store_tests.ml
Labels: package management

#9664 refactor(pkg): simplify some pattern matching
  src/dune_pkg/sys_poll.ml
Labels: package management

#9667 fix(pkg): do not use Pp.newline in errors
  src/dune_pkg/lock_dir.ml
Labels: package management

#9668 test(pkg): pin-depends with opam subdir
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#9676 test: demonstrate checksum computing bugs
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
Labels: package management

#9663 fix(pkg): save locations of repo names
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
Labels: package management

#9681 fix(pkg): missing location in rev store
  src/dune_pkg/opam_repo.ml
Labels: package management

#9669 fix(pkg): directory_entries bug
  src/dune_pkg/rev_store.ml
Labels: package management

#9686 refactor(pkg): remove an unnecessary [result] variable
  src/dune_pkg/opam_solver.ml
Labels: package management

#9670 fix(pkg): improve locations for local path repos
  bin/pkg/pkg_common.ml
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
Labels: package management

#9694 fix(pkg): add more missing locations
  src/dune_pkg/opam_repo.ml
Labels: package management

#9693 fix(pkg): Use function return value
  test/blackbox-tests/test-cases/pkg/invalid-opam-repo-errors.t/run.t
Labels: package management

#9683 Remove `--skip-update` and make it implied when possible
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/rev_store.ml
  test/blackbox-tests/test-cases/pkg/opam-repository-download.t
Labels: package management

#9496 fix: resolve installed binaries to local paths
  doc/changes/9496.md
  otherlibs/stdune/src/map.ml
  otherlibs/stdune/src/map_intf.ml
  src/dune_rules/artifacts.ml
  src/dune_rules/artifacts.mli
  src/dune_rules/artifacts_db.ml
  src/dune_rules/cinaps.ml
  src/dune_rules/coq/coq_config.ml
  src/dune_rules/coq/coq_rules.ml
  src/dune_rules/expander.ml
  src/dune_rules/fdo.ml
  src/dune_rules/inline_tests.ml
  src/dune_rules/jsoo/jsoo_rules.ml
  src/dune_rules/mdx.ml
  src/dune_rules/melange/melange_binary.ml
  src/dune_rules/menhir/menhir_rules.ml
  src/dune_rules/odoc.ml
  src/dune_rules/super_context.ml
  src/dune_rules/super_context.mli
Labels: coq

#9703 pkg: don't generate checksums for local sources
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/source.ml
  test/blackbox-tests/test-cases/dune
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/fetch-local-source.t
  test/blackbox-tests/test-cases/pkg/opam-source-conversion.t
  test/blackbox-tests/utils/dune
  test/blackbox-tests/utils/webserver_oneshot.ml
Labels: package management

#9719 pkg: use a Code_error instead of assert false
  src/dune_rules/pkg_rules.ml
Labels: package management

#9698 refactor(pkg): make remote reading a little more resilient
  src/dune_pkg/rev_store.ml
Labels: package management

#9726 refactor(pkg): sys poll variable improvements
  src/dune_rules/pkg_rules.ml
Labels: package management

#9718 pkg: simple end to end test of package management
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/e2e.t
Labels: package management

#9422 doc: add reference info for cram tests
  doc/index.rst
  doc/reference/cram.rst
  doc/stanzas/cram.rst
  doc/tests.rst
Labels: docs

#9723 fix(pkg): do not copy unnecessary folders/files to package sources
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/source-copy-mask.t
Labels: package management

#9685 feature(pkg): support pin-depends
  bin/pkg/lock.ml
  bin/pkg/pkg_common.ml
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/pinned_package.ml
  src/dune_pkg/pinned_package.mli
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
  src/dune_pkg/source.ml
  src/dune_pkg/source.mli
  src/dune_rules/package.ml
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#9739 chore(pkg): leave comment about sorting
  src/dune_pkg/opam_solver.ml
Labels: package management

#9680 Raise code error when git command fails
  src/dune_engine/process.mli
  src/dune_pkg/rev_store.ml
Labels: package management

#9741 test(pkg): package caching
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/source-caching.t
Labels: package management

#9740 test(pkg): unavailable sources
  test/blackbox-tests/test-cases/pkg/unavailable-package-source.t
Labels: package management

#9747 test(pkg): build independent packages
  test/blackbox-tests/test-cases/pkg/build-single-package.t
Labels: package management

#9742 test(pkg): wait for jobs to finish
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
  test/blackbox-tests/test-cases/pkg/e2e.t
Labels: package management

#9720 pkg: support write-file in expander
  src/dune_rules/pkg_rules.ml
Labels: package management

#9745 fix(pkg): respect global display flags for downloads
  src/dune_pkg/fetch.ml
  src/dune_pkg/rev_store.ml
Labels: package management

#9755 test: fix tests that make assumptions about umask
  test/blackbox-tests/test-cases/directory-targets/copy-sandboxing.t
  test/blackbox-tests/test-cases/directory-targets/remove-write-permissions.t
Labels: test-suite

#9749 test(pkg): share http code
  test/blackbox-tests/utils/dune
  test/blackbox-tests/utils/webserver_oneshot.ml
  test/expect-tests/dune_pkg/dune
  test/expect-tests/dune_pkg/fetch_tests.ml
  test/http/dune
  test/http/http.ml
  test/http/http.mli
Labels: package management

#9760 pkg: user error when non-local->local dep
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/non-local-package-depends-on-local-package-error.t
Labels: package management

#9737 doc: use a hierarchy of index pages
  doc/advanced/index.rst
  doc/explanation/index.rst
  doc/getting-started/index.rst
  doc/howto/index.rst
  doc/index.rst
  doc/misc/index.rst
  doc/reference/index.rst
Labels: docs

#9764 test(pkg): multi project builds
  test/blackbox-tests/test-cases/pkg/multi-project.t
Labels: package management

#9762 refactor(pkg): rename [deps] to [depends]
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/default-exported-env.t
  test/blackbox-tests/test-cases/pkg/exported-env.t
  test/blackbox-tests/test-cases/pkg/file-depends.t
  test/blackbox-tests/test-cases/pkg/gh8325.t
  test/blackbox-tests/test-cases/pkg/installed-binary.t
  test/blackbox-tests/test-cases/pkg/lockdir-validation.t
  test/blackbox-tests/test-cases/pkg/lockfile-deps-respect-constraints.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-filtered-deps.t
  test/blackbox-tests/test-cases/pkg/opam-package-with-setenv.t
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-pkg.t
  test/blackbox-tests/test-cases/pkg/package-cycle.t
  test/blackbox-tests/test-cases/pkg/substitute.t
  test/blackbox-tests/test-cases/pkg/variables.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#9730 refactor(pkg): split lock dir from package rules
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_rules.ml
Labels: package management

#9770 fix(pkg): use all packages in a workspace
  bin/pkg/lock.ml
  bin/pkg/pkg_common.ml
  test/blackbox-tests/test-cases/pkg/multi-project.t
  test/blackbox-tests/test-cases/pkg/opam-package-files-unix-error.t
Labels: package management

#9778 fix(pkg): do not run Memo.run more than once per command
  bin/describe/describe_pkg.ml
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/validate_lock_dir.ml
Labels: package management

#9780 fix(pkg): better error handling for pins
  src/dune_pkg/opam_file.ml
  src/dune_pkg/opam_file.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/resolved_package.ml
  src/dune_rules/package.ml
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
  test/blackbox-tests/test-cases/pkg/opam-file-errors.t
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#9750 pkg: add cond statement for choosing lockdir
  src/dune_lang/cond.ml
  src/dune_lang/cond.mli
  src/dune_lang/dune_lang.ml
  src/dune_pkg/dune
  src/dune_pkg/sys_poll.ml
  src/dune_rules/cond_expand.ml
  src/dune_rules/cond_expand.mli
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/lock-directory-selection.t
Labels: package management

#9771 pkg: reuse downloaded archives within single run
  src/dune_pkg/single_run_file_cache.ml
  src/dune_pkg/single_run_file_cache.mli
  src/dune_pkg/source.ml
  test/blackbox-tests/test-cases/pkg/compute-checksums-when-missing.t
Labels: package management

#9840 bump version to 3.14
  doc/coq.rst
  doc/dune-files.rst
  doc/foreign-code.rst
  doc/hacking.rst
  doc/instrumentation.rst
  doc/melange.rst
  doc/sites.rst
  otherlibs/dune-rpc/private/types.ml
  src/dune_sexp/syntax.ml
  test/blackbox-tests/test-cases/directory-targets/installed-dependency.t
  test/blackbox-tests/test-cases/dune-init.t/run.t
  test/blackbox-tests/test-cases/install/install-stublibs.t/run.t
  test/blackbox-tests/test-cases/melange/basic-install.t
  test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t
Labels: chore

#9763 refactor: unify package variables
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  boot/libs.ml
  src/dune_lang/dune
  src/dune_lang/dune_lang.ml
  src/dune_lang/package_constraint.ml
  src/dune_lang/package_constraint.mli
  src/dune_lang/package_variable_name.ml
  src/dune_lang/package_variable_name.mli
  src/dune_pkg/dune_pkg.ml
  src/dune_pkg/import.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_variable.ml
  src/dune_pkg/package_variable.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/solver_stats.ml
  src/dune_pkg/solver_stats.mli
  src/dune_pkg/substs.ml
  src/dune_pkg/substs.mli
  src/dune_pkg/sys_poll.ml
  src/dune_rules/import.ml
  src/dune_rules/opam_create.ml
  src/dune_rules/pkg_rules.ml
  src/dune_rules/slang_expand.ml
  src/dune_rules/slang_expand.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#9843 fix(pkg): pin-depends and git repos
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/pinned_package.ml
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#7325 doc: add todos for new structure
  doc/advanced/custom-cmxs.rst
  doc/advanced/findlib-dynamic.rst
  doc/advanced/ocaml-syntax.rst
  doc/advanced/package-version.rst
  doc/advanced/profiling-dune.rst
  doc/advanced/variables-artifacts.rst
  doc/caching.rst
  doc/concepts/dependency-spec.rst
  doc/concepts/locks.rst
  doc/concepts/package-spec.rst
  doc/concepts/promotion.rst
  doc/concepts/sandboxing.rst
  doc/concepts/scopes.rst
  doc/concepts/variables.rst
  doc/coq.rst
  doc/cross-compilation.rst
  doc/documentation.rst
  doc/dune-files.rst
  doc/dune-libs.rst
  doc/faq.rst
  doc/foreign-code.rst
  doc/goals.rst
  doc/hacking.rst
  doc/instrumentation.rst
  doc/jsoo.rst
  doc/overview.rst
  doc/quick-start.rst
  doc/rpc.rst
  doc/sites.rst
  doc/tests.rst
  doc/toplevel-integration.rst
  doc/usage.rst
  doc/variants.rst
Labels: docs

#9863 doc: add "How to Install Dune"
  doc/howto/index.rst
  doc/howto/install-dune.rst
  doc/quick-start.rst
Labels: docs
