Repository ocaml/dune, pull requests merged in 2025-09, with the labels that each got.

#12382 [3.20] backport #12329
  doc/changes/12329.md
  src/dune_rules/cram/cram_exec.ml
  test/blackbox-tests/test-cases/cram/test-dir-contents.t
Labels: release

#12383 [3.20] backport #12324
  doc/changes/12324.md
  src/dune_rules/inline_tests.ml
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/js-alias/dune
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/js-alias/js.ml
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
Labels: release

#12384 [3.20] backport #12320
  doc/changes/12320.md
  src/dune_rules/jsoo/jsoo_rules.ml
  test/blackbox-tests/test-cases/jsoo/without_implem.t/run.t
Labels: release

#12388 chore: changelog for 3.20.2
  CHANGES.md
  doc/changes/12242.md
  doc/changes/12245.md
  doc/changes/12251.md
  doc/changes/12320.md
  doc/changes/12324.md
  doc/changes/12329.md
Labels: release

#12236 Expose 'ocamlc -config' parameter 'ox'
  doc/changes/12236.md
  src/ocaml-config/ocaml_config.ml
  src/ocaml-config/ocaml_config.mli
  test/blackbox-tests/test-cases/ocaml-config-ox.t
  test/blackbox-tests/test-cases/oxcaml/ocaml-config-ox-true.t
Labels: oxcaml

#12393 Check for parameterised libraries from the compiler config
  src/dune_rules/buildable_rules.ml
  src/ocaml-config/ocaml_config.ml
  src/ocaml-config/ocaml_config.mli
  src/ocaml/version.ml
  src/ocaml/version.mli
Labels: oxcaml

#12398 [Docs] Add 'edit on github' button to all pages
  doc/conf.py
Labels: docs

#12443 Execute commands in `opam-var-os.t`
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-os.t
Labels: bug, package management, test

#12464 melange: don't emit empty `.js` files for module aliases
  doc/changes/12464.md
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/emit-private.t
  test/blackbox-tests/test-cases/melange/empty-aliases-file.t
  test/blackbox-tests/test-cases/melange/include_subdirs.t/run.t
Labels: melange

#12492 Do not cancel in-progress builds on `main`
  .github/workflows/workflow.yml
Labels: github-actions, github_actions

#12489 tests: Enable dev-tool flag when running dev-tools
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-install.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-which.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-wrapper.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-basic.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-env-path-var.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-no-ocaml-lockfile.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-ocamlformat.t
  test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-relock-on-ocaml-version-change.t
Labels: test-suite

#12497 tests: Do not print internal package structure
  test/blackbox-tests/test-cases/pkg/ignored-dune-lock.t
Labels: test-suite

#12440 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#12505 refactor: Make CLI return lock dir path as `Path.Source.t`
  bin/describe/describe_pkg.ml
  bin/pkg/lock.ml
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/pkg_enabled.ml
  bin/pkg/print_solver_env.ml
  bin/pkg/validate_lock_dir.ml
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
Labels: package management
