Repository ocaml/dune, pull requests merged in 2025-01, with the labels that each got.

#11252 fix(melange): pass `melange.emit`'s `compile_flags` to js emission
  doc/changes/11252.md
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/flags-for-emission.t
Labels: melange

#11254 pkg: precompute directory descendants in rev_store
  otherlibs/stdune/src/path.mli
  src/dune_pkg/rev_store.ml
Labels: package management

#11253 fix(melange): disallow private implementations of public virtual libs
  doc/changes/11253.md
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/virtual-lib-private-impl.t
Labels: melange

#11260 Typo
  doc/tutorials/dune-package-management/dependencies.md
Labels: docs

#11264 pkg: don't expand deps of restricting deps
  src/0install-solver/solver_core.ml
Labels: package management

#11292 Make the notes in the document use consistent markup
  doc/virtual-libraries.rst
Labels: docs

#11268 [Change 10953] Missing explanation
  doc/changes/10953.md
Labels: docs

#11316 refactor: remove unused ocaml function
  src/dune_rules/pkg_toolchain.ml
  src/dune_rules/pkg_toolchain.mli
Labels: refactoring

#11310 fix: package management working with ocaml.5.3.0
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
Labels: bug, package management

#11273 pkg: version comparison fastpath
  vendor/opam/src/format/opamPackage.ml
  vendor/opam/src/format/opamPackage.mli
Labels: package management

#11365 backport #11310: fix: package management working with ocaml.5.3.0
  src/dune_rules/pkg_rules.ml
  src/dune_rules/pkg_toolchain.ml
Labels: release

#11263 pkg: add argument to pkg lock to print perf stats
  bin/lock_dev_tool.ml
  bin/pkg/lock.ml
  bin/pkg/lock.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
Labels: package management

#11370 [3.17] backport #11252: fix(melange): pass `melange.emit`'s `compile_flags` to js emission (#…
  doc/changes/11252.md
  src/dune_rules/melange/melange_rules.ml
  test/blackbox-tests/test-cases/melange/flags-for-emission.t
Labels: release

#11372 [3.17] backport #11253: fix(melange): disallow private implementations of public virtual libs…
  doc/changes/11253.md
  src/dune_rules/melange/melange_rules.ml
Labels: release

#11373 chore: prepare 3.17.2 changelog
  CHANGES.md
  doc/changes/11248.md
  doc/changes/11252.md
  doc/changes/11253.md
  doc/changes/11304.md
Labels: release

#11374 chore: changelog dune 3.17.2
  CHANGES.md
  doc/changes/11248.md
  doc/changes/11252.md
  doc/changes/11253.md
  doc/changes/11304.md
Labels: release

#11400 fix: typo in contributor name
  CHANGES.md
Labels: docs

#11398 refactor(pkg): cache transient sets
  src/sat/sat.ml
Labels: refactoring

#11392 refactor: add type equality to remove pointless conversion
  src/dune_lang/action.ml
  src/dune_lang/action.mli
  src/dune_pkg/opam_solver.ml
Labels: refactoring

#11395 refactor(pkg): lazy dependency evaluation
  src/dune_pkg/opam_solver.ml
Labels: refactoring

#11403 doc: Avoid title case and make FAQs all questions
  doc/faq.rst
Labels: docs

#11402 Allow dash in dune init project name
  bin/dune_init.ml
  bin/dune_init.mli
  bin/init.ml
  doc/changes/11402.md
  test/blackbox-tests/test-cases/dune-init/github11210.t
Labels: cli

#11122 Update promotion.rst to explain mode promote
  doc/concepts/promotion.rst
Labels: docs

#11414 refactor(sat): move simpify to own function
  src/sat/sat.ml
Labels: refactoring
