Repository ocaml/dune, pull requests merged in 2025-05, with the labels that each got.

#11726 fix(pkg): handle empty ID_LIKE
  src/dune_pkg/sys_poll.ml
Labels: package management

#11222 Adapt JSOO rules for new --effects= option
  src/dune_rules/jsoo/jsoo_rules.ml
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/bin/bin1.ml
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/bin/bin2.ml
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/bin/bin3.ml
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/bin/dune
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/dune
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/dune-project
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/lib/dune
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/lib/library1.ml
  test/blackbox-tests/test-cases/jsoo/jsoo-config-effects.t/run.t
  test/blackbox-tests/test-cases/jsoo/no-check-prim.t/run.t
  test/blackbox-tests/test-cases/wasmoo/no-check-prim.t/run.t
Labels: jsoo

#11725 test: non-relocatable variables are using the wrong path
  test/blackbox-tests/test-cases/pkg/toolchain-variables.t
Labels: package management, test

#11740 refactor(melange_rules): extract `Output_kind.t`
  src/dune_rules/melange/melange_rules.ml
Labels: melange

#11742 refactor(melange_rules): add `cmj_glob` under the `cmj_includes` scope
  src/dune_rules/melange/melange_rules.ml
Labels: melange

#11738 Fix #11698
  src/dune_pkg/local_package.ml
  test/blackbox-tests/test-cases/pkg/depopts/gh11698.t
Labels: package management

#11744 test: clean up melange runtime_deps tests
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps-edge-cases.t
  test/blackbox-tests/test-cases/melange/emit-with-runtime-deps.t
  test/blackbox-tests/test-cases/melange/public-library-with-runtime-deps.t
Labels: melange, test

#11743 refactor: improve code sharing / data structures for `Melange_rules.Runtime_deps`
  src/dune_rules/melange/melange_rules.ml
Labels: melange

#11704 chore: changelog for 3.18.2
  CHANGES.md
Labels: release

#11765 refactor: remove a bunch of unusable opam code
  vendor/opam/src/core/opamDirTrack.ml
  vendor/opam/src/core/opamDirTrack.mli
  vendor/opam/src/core/opamFilename.ml
  vendor/opam/src/core/opamFilename.mli
  vendor/opam/src/core/opamProcess.ml
  vendor/opam/src/core/opamProcess.mli
  vendor/opam/src/core/opamSystem.ml
  vendor/opam/src/core/opamSystem.mli
Labels: package management

#11723 pkg: don't depend on dune_digest
  src/dune_pkg/checksum.ml
  src/dune_pkg/checksum.mli
  src/dune_pkg/dune
  src/dune_pkg/local_package.ml
  src/dune_pkg/md5.ml
  src/dune_pkg/md5.mli
  src/dune_pkg/md5_stubs.c
  src/dune_pkg/source.ml
Labels: package management

#11767 Path.drop_prefix: adapt to Win32
  doc/changes/11767.md
  otherlibs/stdune/src/path.ml
  otherlibs/stdune/src/path.mli
  otherlibs/stdune/src/string.ml
  otherlibs/stdune/src/string.mli
Labels: bug

#11773 feature: depopt selection in the workspace
  bin/pkg/lock.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/depopts/workspace-select.t
  test/blackbox-tests/test-cases/pkg/unavailable-packages.t
Labels: package management

#11794 fix(pkg): check reachabilility before looking for compiler
  src/dune_pkg/opam_solver.ml
Labels: package management

#11804 [3.18] fix datetime error
  CHANGES.md
Labels: release

#11795 fix(pkg): do include files from unreachable packages
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/post-deps-solving.t
Labels: package management

#11489 Experimental portable lockdirs
  bin/describe/describe_depexts.ml
  bin/describe/describe_pkg.ml
  bin/lock_dev_tool.ml
  bin/pkg/lock.ml
  bin/pkg/lock.mli
  bin/pkg/outdated.ml
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  bin/pkg/validate_lock_dir.ml
  boot/configure.ml
  flake.nix
  src/dune_lang/package_variable_name.ml
  src/dune_lang/package_variable_name.mli
  src/dune_lang/package_version.mli
  src/dune_pkg/file_entry.ml
  src/dune_pkg/file_entry.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/lock_pkg.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/opam_solver.mli
  src/dune_pkg/package_universe.ml
  src/dune_pkg/package_universe.mli
  src/dune_pkg/package_version.mli
  src/dune_pkg/solver_env.ml
  src/dune_pkg/solver_env.mli
  src/dune_pkg/sys_poll.ml
  src/dune_pkg/variable_value.ml
  src/dune_pkg/variable_value.mli
  src/dune_rules/compile_time.ml
  src/dune_rules/compile_time.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/lock_dir.ml
  src/dune_rules/lock_dir.mli
  src/dune_rules/pkg_rules.ml
  src/dune_rules/setup.defaults.ml
  src/dune_rules/setup.mli
  src/dune_rules/workspace.ml
  src/dune_rules/workspace.mli
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/dune
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-basic.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-custom-platforms.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-partial-solve.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-platform-dependant-dependencies.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-platform-dependant-version-extra-files.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-platform-dependant-version.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#11805 fix: typo in changelog datetime
  CHANGES.md
Labels: docs

#11806 [3.19] prepare 3.19.0~alpha0 changelog
  CHANGES.md
  doc/changes/11547.md
  doc/changes/11600.md
  doc/changes/11619.md
  doc/changes/11622.md
  doc/changes/11683.md
  doc/changes/11707.md
  doc/changes/11712.md
  doc/changes/11729.md
  doc/changes/11760.md
  doc/changes/11767.md
Labels: release

#11823 Remove some unused logic from exec
  bin/exec.ml
Labels: cli, tools

#11830 [3.19] changelog for 3.19.0
  CHANGES.md
Labels: release

#11835 Add standalone doc for dune-project global fields
  doc/reference/dune-project/authors.rst
  doc/reference/dune-project/bug_reports.rst
  doc/reference/dune-project/documentation.rst
  doc/reference/dune-project/generate_opam_files.rst
  doc/reference/dune-project/homepage.rst
  doc/reference/dune-project/index.rst
  doc/reference/dune-project/license.rst
  doc/reference/dune-project/maintainers.rst
  doc/reference/dune-project/maintenance_intent.rst
  doc/reference/dune-project/package.rst
  doc/reference/dune-project/source.rst
Labels: docs

#11864 Set a default platform for solving deps in pkg tests
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-os.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-basic.t
Labels: package management
