Repository ocaml/dune, pull requests merged in 2025-06, with the labels that each got.

#11877 doc: clarify generic type in rpc server
  bin/common.ml
  src/dune_rpc_impl/server.ml
  src/dune_rpc_impl/server.mli
  src/dune_rules_rpc/dune_rules_rpc.ml
  src/dune_rules_rpc/dune_rules_rpc.mli
Labels: docs

#11833 Display a warning when dune builds via RPC
  bin/arg.ml
  bin/arg.mli
  bin/build_cmd.ml
  bin/common.ml
  bin/common.mli
  bin/tools/tools_common.ml
  src/dune_cache/config.ml
  src/dune_cache/config.mli
  src/dune_cache_storage/mode.ml
  src/dune_cache_storage/mode.mli
  src/dune_config_file/display.ml
  src/dune_config_file/display.mli
  src/dune_config_file/dune_config_file.ml
  src/dune_config_file/dune_config_file.mli
  src/dune_engine/cache_debug_flags.ml
  src/dune_engine/clflags.ml
  src/dune_engine/clflags.mli
  src/dune_engine/display.ml
  src/dune_engine/display.mli
  src/dune_engine/report_errors_config.ml
  src/dune_engine/scheduler.ml
  src/dune_engine/scheduler.mli
  src/dune_graph/graph.ml
  src/dune_graph/graph.mli
  src/dune_lang/dep_conf.ml
  src/dune_lang/dep_conf.mli
  src/dune_rpc_impl/watch_mode_config.ml
  src/dune_rpc_impl/watch_mode_config.mli
  src/dune_util/global_lock.ml
  src/dune_util/global_lock.mli
  src/dune_util/log.ml
  src/dune_util/log.mli
  src/source/only_packages.ml
  src/source/only_packages.mli
  src/source/workspace.ml
  src/source/workspace.mli
  test/blackbox-tests/test-cases/watching/watching-eager-concurrent-build-command.t
  test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
Labels: build

#11883 chore(ci): pin switch to local version
  .github/workflows/workflow.yml
Labels: chore

#11884 chore(version): bump to 3.20 (latest)
  bench/dune
  bench/monorepo/bench.Dockerfile
  chrome-trace.opam
  dune-action-plugin.opam
  dune-build-info.opam
  dune-configurator.opam
  dune-glob.opam
  dune-private-libs.opam
  dune-project
  dune-rpc-lwt.opam
  dune-rpc.opam
  dune-site.opam
  dyn.opam
  ocamlc-loc.opam
  ordering.opam
  src/dune_cache/dune
  src/dune_config_file/dune
  src/dune_digest/dune
  src/dune_engine/dune
  src/dune_file_watcher/dune
  src/dune_pkg/dune
  src/dune_rpc_impl/dune
  src/dune_rpc_server/dune
  src/dune_rules/dune
  src/dune_rules_rpc/dune
  src/dune_tui/dune
  src/install/dune
  src/promote/dune
  src/source/dune
  src/upgrader/dune
  stdune.opam
  test/blackbox-tests/test-cases/ctypes/dune
  test/blackbox-tests/test-cases/dune
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/utils/dune
  test/expect-tests/dune_action_plugin/dune
  test/expect-tests/dune_file_watcher/dune
  test/expect-tests/inotify_tests/dune
  xdg.opam
Labels: chore

#11892 chore(ci): bump msvc, mingw to 5.3 and reorganise ci matrix
  .github/workflows/workflow.yml
Labels: chore

#11929 chore: Bump ocaml version used in tests
  Makefile
  doc/hacking.rst
  doc/tutorials/developing-with-dune/introduction.md
Labels: chore

#11928 chore: update makefile to support latest dune
  Makefile
Labels: chore

#11933 Portable lockdirs respects custom solver_env
  bin/pkg/lock.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/sys_poll.ml
  src/dune_rules/lock_dir.ml
  test/blackbox-tests/test-cases/pkg/helpers.sh
  test/blackbox-tests/test-cases/pkg/ocaml-compiler.t
  test/blackbox-tests/test-cases/pkg/opam-var/opam-var-os.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-custom-platforms.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-custom-solver-env.t
  test/blackbox-tests/test-cases/pkg/portable-lockdirs/portable-lockdirs-partial-solve.t
Labels: package management
