Repository ocaml/dune, pull requests merged in 2025-04, with the labels that each got.

#11588 chore(mirage): bump to setup-ocaml@v3
  .github/workflows/mirage.yml
Labels: chore

#11594 Update CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#11599 chore: prepare 3.18.0
  CHANGES.md
Labels: release

#11582 pkg: remove broken symlinks from package sources
  otherlibs/stdune/src/fpath.ml
  otherlibs/stdune/src/fpath.mli
  otherlibs/stdune/src/path.ml
  otherlibs/stdune/src/path.mli
  src/dune_rules/fetch_rules.ml
  src/dune_rules/pkg_rules.ml
  test/blackbox-tests/test-cases/pkg/broken-symlink-in-dependency.t
  test/blackbox-tests/test-cases/pkg/dune
Labels: package management

#11535 Add the warning flag to the C/C++ compiler invocation
  src/dune_rules/cc_flags.ml
  src/dune_rules/cc_flags.mli
  src/dune_rules/cc_rules.ml
  src/dune_rules/cc_rules.mli
  src/dune_rules/foreign_rules.ml
  src/dune_rules/gen_rules.ml
  src/dune_rules/lib_config.ml
  src/dune_rules/lib_rules.ml
  src/dune_rules/ocaml_flags_db.ml
  src/ocaml-config/ocaml_config.ml
  src/ocaml-config/ocaml_config.mli
  test/blackbox-tests/test-cases/cxx-flags.t/run.t
  test/blackbox-tests/test-cases/foreign-stubs/c-flags.t/run.t
  test/blackbox-tests/test-cases/variables/var-cc.t/run.t
  test/expect-tests/findlib_tests.ml
Labels: c-bindings

#11547 test: cram tests are run twice when both aliases are built
  doc/changes/11547.md
  src/dune_rules/cram/cram_rules.ml
  test/blackbox-tests/test-cases/cram/cram-double-alias.t
  test/blackbox-tests/test-cases/promote/promote-file-to-dir.t
Labels: test

#11613 Introduce a flag for binary dev tools
  bin/lock_dev_tool.ml
  boot/configure.ml
  flake.nix
  src/dune_rules/compile_time.ml
  src/dune_rules/compile_time.mli
  src/dune_rules/setup.defaults.ml
  src/dune_rules/setup.mli
Labels: package management, config

#11559 test: dune exec not updating arg0
  bin/coq/coqtop.ml
  bin/exec.ml
  bin/import.ml
  bin/ocaml/doc.ml
  bin/ocaml/utop.ml
  bin/tools/ocamlformat.ml
  bin/tools/ocamllsp.ml
  otherlibs/stdune/src/proc.ml
  otherlibs/stdune/src/proc.mli
  test/blackbox-tests/test-cases/exec-bin.t
  test/blackbox-tests/test-cases/github11527.t
Labels: bug, cli

#11626 [3.18] backport #11619
  doc/changes/11619.md
  otherlibs/configurator/src/v1.ml
  otherlibs/configurator/test/blackbox-tests/pkg-config-args.t/run.t
Labels: release

#11235 [Reference manual/Coq] Fix label for VERNAC EXTEND
  doc/coq.rst
Labels: docs, coq

#11640 chore(test): move exec cram tests to exec/
  test/blackbox-tests/test-cases/exec/dune-build-dir-exec-1101.t/dune
  test/blackbox-tests/test-cases/exec/dune-build-dir-exec-1101.t/dune-project
  test/blackbox-tests/test-cases/exec/dune-build-dir-exec-1101.t/main.ml
  test/blackbox-tests/test-cases/exec/dune-build-dir-exec-1101.t/run.t
  test/blackbox-tests/test-cases/exec/exec-bin.t
  test/blackbox-tests/test-cases/exec/exec-cmd.t/bar.ml
  test/blackbox-tests/test-cases/exec/exec-cmd.t/dune
  test/blackbox-tests/test-cases/exec/exec-cmd.t/dune-project
  test/blackbox-tests/test-cases/exec/exec-cmd.t/foo.ml
  test/blackbox-tests/test-cases/exec/exec-cmd.t/foo.opam
  test/blackbox-tests/test-cases/exec/exec-cmd.t/run.t
  test/blackbox-tests/test-cases/exec/exec-missing.t/dune
  test/blackbox-tests/test-cases/exec/exec-missing.t/dune-project
  test/blackbox-tests/test-cases/exec/exec-missing.t/run.t
  test/blackbox-tests/test-cases/exec/exec-missing.t/x.ml
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/dune
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/dune-project
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/foo.ml
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/foo/bar.ml
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/foo/dune
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/foo/dune-project
  test/blackbox-tests/test-cases/exec/hints-root-executables.t/run.t
  test/blackbox-tests/test-cases/exec/public_name-exe.t/dune
  test/blackbox-tests/test-cases/exec/public_name-exe.t/dune-project
  test/blackbox-tests/test-cases/exec/public_name-exe.t/mypackage.opam
  test/blackbox-tests/test-cases/exec/public_name-exe.t/run.t
Labels: test-suite

#11642 Minor documentation fixes
  doc/reference/dune/dirs.rst
  doc/reference/dune/include_subdirs.rst
Labels: docs

#11655 fix(pkg): relocate run_with_path to sandbox correctly
  src/dune_rules/run_with_path.ml
  test/blackbox-tests/test-cases/pkg/run-local.t
Labels: bug, package management

#11651 Fix typos, update docs to Menhir lang 3.0
  doc/explanation/package-management.md
  doc/explanation/tour/tests.rst
  doc/howto/override-default-entrypoint.rst
  doc/reference/aliases/ocaml-index.rst
  doc/reference/dune-workspace/lock_dir.rst
  doc/reference/dune-workspace/repository.rst
  doc/reference/dune/menhir.rst
  doc/reference/dune/rule.rst
  doc/sites.rst
  doc/tutorials/developing-with-dune/development-cycle.md
  doc/tutorials/developing-with-dune/introduction/dune-project
Labels: docs

#11622 Allow rpc-triggered builds in eager watch mode
  bin/build_cmd.ml
  bin/common.ml
  doc/changes/11622.md
  doc/rpc.rst
  src/dune_rpc_impl/server.ml
  src/dune_rpc_impl/server.mli
  test/blackbox-tests/test-cases/watching/watching-eager-with-rpc.t
Labels: build

#11694 test(melange): add `(emit_stdlib false)` to `melange/flags.t`
  test/blackbox-tests/test-cases/melange/flags.t
Labels: melange, test

#11695 test(melange): add `emit_stdlib false` to recompile-dependents.t
  test/blackbox-tests/test-cases/melange/recompile-dependents.t
Labels: melange, test

#11700 [3.18] Backport #11639 for OCaml 5.4 support
  otherlibs/stdune/src/signal.ml
Labels: release

#11702 chore: changelog for dune.3.18.2
  CHANGES.md
Labels: release

#11478 chore: bump dune version to 3.18
  bench/monorepo/bench.Dockerfile
  chrome-trace.opam
  dune-action-plugin.opam
  dune-build-info.opam
  dune-configurator.opam
  dune-glob.opam
  dune-private-libs.opam
  dune-project
  dune-rpc-lwt.opam
  dune-rpc.opam
  dune-site.opam
  dune.opam
  dyn.opam
  ocamlc-loc.opam
  ordering.opam
  stdune.opam
  xdg.opam
Labels: chore

#11696 chore(nix): improve nix devShell#scope
  flake.nix
Labels: nix

#11703 [3.18] fix: missing keyword in changelog
  CHANGES.md
Labels: release
