Repository ocaml/dune, pull requests merged in 2025-03, with the labels that each got.

#11497 pkg: minor fix is sys_poll library
  src/dune_pkg/sys_poll.ml
Labels: bug, package management

#11498 pkg: handle opam string interp special case
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/package-name-with-plus-character.t
Labels: package management

#11512 pkg: handle undefined vars in command filters
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/convert-opam-commands.t
  test/blackbox-tests/test-cases/pkg/partial-filter-evaluation.t
Labels: package management

#11515 pkg: fix opam conflicts "expected formula to be a conjunction"
  src/dune_pkg/local_package.ml
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_dependency.mli
  test/blackbox-tests/test-cases/pkg/conflicts.t
Labels: bug, package management

#11516 Doc sites fix
  doc/sites.rst
Labels: docs

#11524 test: repro #11523 (symlinks in directory targets)
  test/blackbox-tests/test-cases/directory-targets/cache-symlink.t
Labels: shared-cache, test

#11513 fix: use build and install instructions from opam on pinning
  bin/lock_dev_tool.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/local_package.mli
  src/dune_pkg/pin_stanza.ml
  src/dune_pkg/resolved_package.ml
  src/dune_pkg/resolved_package.mli
  test/blackbox-tests/test-cases/pkg/pin-stanza/build-command-dune-project.t
Labels: bug, package management

#11526 Prefer `int main(void)` to `int main()` in C examples
  doc/dune-libs.rst
  otherlibs/configurator/test/blackbox-tests/configurator.t/c_test/run.ml
Labels: docs

#11529 doc: update wasm_of_ocaml installation instructions
  doc/wasmoo.rst
  src/dune_rules/jsoo/jsoo_rules.ml
Labels: docs, jsoo

#11531 Improve include doc to reference dynamic_include for generated files
  doc/reference/dune/dynamic_include.rst
  doc/reference/dune/include.rst
Labels: docs

#11511 pkg: support for dependencies compressed with zip
  bin/pkg/pkg_common.ml
  src/dune_pkg/archive_driver.ml
  src/dune_pkg/archive_driver.mli
  src/dune_pkg/fetch.ml
  src/dune_pkg/mount.ml
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/rev_store.ml
  src/dune_pkg/tar.ml
  src/dune_pkg/tar.mli
Labels: package management

#11534 test: repro for #11533 (permissions in cache)
  test/blackbox-tests/test-cases/directory-targets/cache-permissions.t
Labels: shared-cache, package management, test

#11378 pkg: allow pkg for release builds
  bin/common.ml
  test/blackbox-tests/test-cases/pkg/ignore-lock-package-build.t
Labels: package management

#11554 pkg: handle case where dune violates project deps
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/unsatisfied-version-constraint-on-dune.t
Labels: package management

#11541 Cache: only store executable permission bit
  doc/changes/11541.md
  src/dune_digest/digest.ml
  src/dune_digest/digest.mli
  test/blackbox-tests/test-cases/directory-targets/cache-permissions.t
  test/expect-tests/digest/digest_tests.ml
Labels: shared-cache

#11437 Windows: retry a file remove - a virus checker might lock files
  doc/changes/11437.md
  otherlibs/stdune/src/fpath.ml
Labels: windows

#11586 [3.18] changelog for 3.18.0~alpha0
  CHANGES.md
  doc/changes/10953.md
  doc/changes/11166.md
  doc/changes/11172.md
  doc/changes/11173.md
  doc/changes/11234.md
  doc/changes/11274.md
  doc/changes/11307.md
  doc/changes/11308.md
  doc/changes/11402.md
  doc/changes/11404.md
  doc/changes/11437.md
  doc/changes/11503.md
  doc/changes/11504.md
  doc/changes/11541.md
Labels: release
