Repository ocaml/dune, pull requests merged in 2025-02, with the labels that each got.

#11413 refactor(sat): remove useless argument of [Decided]
  src/sat/sat.ml
Labels: refactoring

#11362 Concurrent fiber solver
  otherlibs/stdune/src/hashtbl.ml
  otherlibs/stdune/src/hashtbl_intf.ml
  otherlibs/stdune/src/table.ml
  otherlibs/stdune/src/table.mli
  src/dune_pkg/opam_solver.ml
Labels: solver

#11301 refactor(pkg): buffer string reading
  vendor/opam-file-format/opamLexer.mll
Labels: refactoring

#11302 refactor(pkg): reuse opam buffer for parsing
  vendor/opam-file-format/opamLexer.mll
Labels: refactoring

#11441 bug_report.md: add missing :
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs

#11439 refactor: cleanups in the opam solver
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_universe.ml
  src/dune_pkg/resolve_opam_formula.ml
  src/dune_pkg/resolve_opam_formula.mli
Labels: refactoring, solver

#11449 chore(ci): remove opam unsupported compilers
  .github/workflows/workflow.yml
  boot/bootstrap.ml
  doc/reference/dune-workspace/index.rst
  doc/reference/ordered-set-language.rst
  dune-configurator.opam
  dune-project
  dune.opam
  dune.opam.template
  test/blackbox-tests/test-cases/bigarray.t/run.t
  test/blackbox-tests/test-cases/utop/dune
Labels: chore

#11307 Shorter path for inline-tests
  doc/changes/11307.md
  src/dune_rules/dir_status.ml
  src/dune_rules/inline_tests.ml
  src/dune_rules/inline_tests_info.ml
  src/dune_rules/inline_tests_info.mli
  test/blackbox-tests/test-cases/inline_tests/parallel.t/run.t
  test/blackbox-tests/test-cases/inline_tests/simple.t
Labels: test-suite

#11202 test: Repro 'dune fmt' crash in presence of Nix result
  src/dune_engine/hooks.ml
  src/promote/diff_promotion.ml
  test/blackbox-tests/test-cases/read-only-symlink-target.t/.ocamlformat
  test/blackbox-tests/test-cases/read-only-symlink-target.t/dune
  test/blackbox-tests/test-cases/read-only-symlink-target.t/dune-project
  test/blackbox-tests/test-cases/read-only-symlink-target.t/ocamlformat.ml
  test/blackbox-tests/test-cases/read-only-symlink-target.t/run.t
Labels: nix

#11350 refactor: specialize string functions for opam's parser string cache
  vendor/opam-file-format/opamLexer.mll
Labels: refactoring

#11226 Fix directory targets with empty subdirs
  src/dune_cache/local.ml
  src/dune_cache/shared.ml
  src/dune_cache/trimmer.ml
  src/dune_cache_storage/dune_cache_storage.ml
  src/dune_cache_storage/dune_cache_storage.mli
  src/dune_engine/build_system.ml
  src/dune_engine/build_system.mli
  src/dune_engine/rule_cache.ml
  src/dune_engine/target_promotion.ml
  src/dune_targets/dune_targets.ml
  src/dune_targets/dune_targets.mli
  src/fs/fs.ml
  test/blackbox-tests/test-cases/directory-targets/subdirs-only.t
  test/blackbox-tests/test-cases/dune-cache/empty-dir.t
  test/blackbox-tests/test-cases/promote/deep-subdir.t
Labels: bug, shared-cache, engine

#11461 nix: fix build with Melange for 5.2
  flake.lock
  flake.nix
Labels: melange, nix

#11453 refactor(pkg): unrefutable constraints
  src/dune_pkg/opam_repo.ml
  src/dune_pkg/opam_repo.mli
  src/dune_pkg/opam_solver.ml
  test/blackbox-tests/test-cases/pkg/conflicts.t
  test/blackbox-tests/test-cases/pkg/gh11265.t
  test/blackbox-tests/test-cases/pkg/lockfile-generation.t/run.t
  test/blackbox-tests/test-cases/pkg/ocamlformat/ocamlformat-relaxed-version-constraints.t
Labels: package management

#11473 test: promote describe-workspace-pp tests
  test/blackbox-tests/test-cases/describe/describe-workspace-pp.t
  test/blackbox-tests/test-cases/describe/describe.t
Labels: chore, test

#11471 fix(pkg): context type set incorrectly
  src/dune_rules/context.ml
Labels: package management, chore

#11465 refactor(pkg): reduce local formula matching
  src/dune_pkg/opam_solver.ml
Labels: package management

#11479 fix(ci): build doc with LC_ALL=C
  .github/workflows/workflow.yml
Labels: docs

#11446 fix: support package pinning via http+tar
  bin/pkg/pkg_common.ml
  src/dune_pkg/fetch.ml
  src/dune_pkg/mount.ml
  src/dune_pkg/opamUrl0.ml
  src/dune_pkg/opamUrl0.mli
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/source.ml
  src/dune_pkg/source.mli
  test/blackbox-tests/test-cases/pkg/dune
  test/blackbox-tests/test-cases/pkg/pin-depends.t
Labels: package management

#11480 chore: promote tests with new JSOO version
  test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
Labels: chore

#11462 melange: update Melange version in Dune to 5.0
  dune.opam
  dune.opam.template
  flake.lock
  flake.nix
  test/blackbox-tests/test-cases/melange/flags-for-emission.t
  test/blackbox-tests/test-cases/melange/private-lib-dep.t
Labels: melange

#11404 Support not in package dependencies constraints
  doc/changes/11404.md
  src/dune_lang/package_constraint.ml
  src/dune_lang/package_constraint.mli
  src/dune_pkg/package_dependency.ml
  src/dune_rules/opam_create.ml
  test/blackbox-tests/test-cases/dune-project-meta/binops.t
  test/blackbox-tests/test-cases/dune-project-meta/operators.t
  test/blackbox-tests/test-cases/pkg/additional-constraints.t
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
Labels: solver

#11487 Require js_of_ocaml >= 6
  dune.opam
  dune.opam.template
Labels: chore

#11488 Require minimal ppxlib version
  dune.opam
  dune.opam.template
Labels: chore

#11495 doc: Fix markup and URL targets of wasm_of_ocaml docs
  doc/wasmoo.rst
Labels: docs

#11492 pkg: fix bug where multiple conflicts causes conlficts to be ignored
  src/dune_pkg/dependency_formula.ml
  src/dune_pkg/local_package.ml
  src/dune_pkg/opam_solver.ml
  src/dune_pkg/package_dependency.ml
  src/dune_pkg/package_dependency.mli
  test/blackbox-tests/test-cases/pkg/gh11265.t
Labels: package management

#11494 pkg: minimize number of packages flagged avoid-version
  bin/pkg/pkg_common.ml
  bin/pkg/pkg_common.mli
  src/dune_pkg/lock_dir.ml
  src/dune_pkg/lock_dir.mli
  src/dune_pkg/opam_solver.ml
  src/sat/sat.ml
  src/sat/sat.mli
  test/blackbox-tests/test-cases/pkg/opam-solver-or.t
  test/blackbox-tests/test-cases/pkg/solve-compiler-dependency.t
  test/expect-tests/dune_pkg/dune_pkg_unit_tests.ml
Labels: package management

#11499 chore(ci): disable test in CI
  otherlibs/dune-site/test/dune
Labels: bug, test-suite

#11504 Display Windows `NTSTATUS` exit codes in hex
  doc/changes/11504.md
  src/dune_engine/process.ml
Labels: windows

#11503 Preserve flags ordering in Merlin configuration files.
  doc/changes/11503.md
  src/dune_rules/merlin/merlin.ml
  test/blackbox-tests/test-cases/github2206.t/run.t
  test/blackbox-tests/test-cases/melange/merlin.t
  test/blackbox-tests/test-cases/merlin/github1946.t/run.t
  test/blackbox-tests/test-cases/merlin/granularity.t
  test/blackbox-tests/test-cases/merlin/include-subdirs-qualified.t
  test/blackbox-tests/test-cases/merlin/instrumentation.t/run.t
  test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t
  test/blackbox-tests/test-cases/merlin/per-module-pp.t/run.t
  test/blackbox-tests/test-cases/merlin/server.t/run.t
  test/blackbox-tests/test-cases/merlin/unit-names-merlin-gh1233.t/run.t
Labels: merlin
